python A_FormatPredictions.py ../1PooledPredictions/AbsCIBERSORT_CellMixtures_ImmunoStates-Full.tsv ../../TrueProportions/TruePropsCellMix.tsv > ReformattedPredictions/AbsCIBERSORT_CellMixtures_ImmunoStates-Full.tsv
python A_FormatPredictions.py ../1PooledPredictions/CIBERSORT_CellMixtures_LM22-Full.tsv ../../TrueProportions/TruePropsCellMix.tsv > ReformattedPredictions/CIBERSORT_CellMixtures_LM22-Full.tsv
python A_FormatPredictions.py ../1PooledPredictions/DCQ_CellMixtures_LM22-Full.tsv ../../TrueProportions/TruePropsCellMix.tsv > ReformattedPredictions/DCQ_CellMixtures_LM22-Full.tsv
python A_FormatPredictions.py ../1PooledPredictions/DeconRNASeq_CellMixtures_LM22-Full.tsv ../../TrueProportions/TruePropsCellMix.tsv > ReformattedPredictions/DeconRNASeq_CellMixtures_LM22-Full.tsv
python A_FormatPredictions.py ../1PooledPredictions/EPIC_CellMixtures_HPCA-Stromal.tsv ../../TrueProportions/TruePropsCellMix.tsv > ReformattedPredictions/EPIC_CellMixtures_HPCA-Stromal.tsv
python A_FormatPredictions.py ../1PooledPredictions/GEDIT_CellMixtures_EPIC-BCIC.tsv ../../TrueProportions/TruePropsCellMix.tsv > ReformattedPredictions/GEDIT_CellMixtures_EPIC-BCIC.tsv
python A_FormatPredictions.py ../1PooledPredictions/MCP-counter_CellMixtures_default.tsv ../../TrueProportions/TruePropsCellMix.tsv > ReformattedPredictions/MCP-counter_CellMixtures_default.tsv
python A_FormatPredictions.py ../1PooledPredictions/SaVanT_CellMixtures_SkinSignaturesV1.tsv ../../TrueProportions/TruePropsCellMix.tsv > ReformattedPredictions/SaVanT_CellMixtures_SkinSignaturesV1.tsv
python A_FormatPredictions.py ../1PooledPredictions/dtangle_CellMixtures_SkinSignaturesV1.tsv ../../TrueProportions/TruePropsCellMix.tsv > ReformattedPredictions/dtangle_CellMixtures_SkinSignaturesV1.tsv
python A_FormatPredictions.py ../1PooledPredictions/nnls_CellMixtures_LM22-Full.tsv ../../TrueProportions/TruePropsCellMix.tsv > ReformattedPredictions/nnls_CellMixtures_LM22-Full.tsv
python A_FormatPredictions.py ../1PooledPredictions/quanTIseq_CellMixtures_default.tsv ../../TrueProportions/TruePropsCellMix.tsv > ReformattedPredictions/quanTIseq_CellMixtures_default.tsv
python A_FormatPredictions.py ../1PooledPredictions/xCell_CellMixtures_default.tsv ../../TrueProportions/TruePropsCellMix.tsv > ReformattedPredictions/xCell_CellMixtures_default.tsv
python A_FormatPredictions.py ../1PooledPredictions/AbsCIBERSORT_PBMC1NormMix_LM22-Full.tsv ../../TrueProportions/TruePropsPBMC1.tsv > ReformattedPredictions/AbsCIBERSORT_PBMC1NormMix_LM22-Full.tsv
python A_FormatPredictions.py ../1PooledPredictions/CIBERSORT_PBMC1NormMix_LM22-Full.tsv ../../TrueProportions/TruePropsPBMC1.tsv > ReformattedPredictions/CIBERSORT_PBMC1NormMix_LM22-Full.tsv
python A_FormatPredictions.py ../1PooledPredictions/DCQ_PBMC1NormMix_EPIC-BCIC.tsv ../../TrueProportions/TruePropsPBMC1.tsv > ReformattedPredictions/DCQ_PBMC1NormMix_EPIC-BCIC.tsv
python A_FormatPredictions.py ../1PooledPredictions/DeconRNASeq_PBMC1NormMix_LM22-Full.tsv ../../TrueProportions/TruePropsPBMC1.tsv > ReformattedPredictions/DeconRNASeq_PBMC1NormMix_LM22-Full.tsv
python A_FormatPredictions.py ../1PooledPredictions/EPIC_PBMC1NormMix_EPIC-BCIC.tsv ../../TrueProportions/TruePropsPBMC1.tsv > ReformattedPredictions/EPIC_PBMC1NormMix_EPIC-BCIC.tsv
python A_FormatPredictions.py ../1PooledPredictions/GEDIT_PBMC1NormMix_EPIC-BCIC.tsv ../../TrueProportions/TruePropsPBMC1.tsv > ReformattedPredictions/GEDIT_PBMC1NormMix_EPIC-BCIC.tsv
python A_FormatPredictions.py ../1PooledPredictions/MCP-counter_PBMC1NormMix_default.tsv ../../TrueProportions/TruePropsPBMC1.tsv > ReformattedPredictions/MCP-counter_PBMC1NormMix_default.tsv
python A_FormatPredictions.py ../1PooledPredictions/SaVanT_PBMC1NormMix_SkinSignaturesV1.tsv ../../TrueProportions/TruePropsPBMC1.tsv > ReformattedPredictions/SaVanT_PBMC1NormMix_SkinSignaturesV1.tsv
python A_FormatPredictions.py ../1PooledPredictions/dtangle_PBMC1NormMix_SkinSignaturesV1.tsv ../../TrueProportions/TruePropsPBMC1.tsv > ReformattedPredictions/dtangle_PBMC1NormMix_SkinSignaturesV1.tsv
python A_FormatPredictions.py ../1PooledPredictions/nnls_PBMC1NormMix_LM22-Full.tsv ../../TrueProportions/TruePropsPBMC1.tsv > ReformattedPredictions/nnls_PBMC1NormMix_LM22-Full.tsv
python A_FormatPredictions.py ../1PooledPredictions/quanTIseq_PBMC1NormMix_default.tsv ../../TrueProportions/TruePropsPBMC1.tsv > ReformattedPredictions/quanTIseq_PBMC1NormMix_default.tsv
python A_FormatPredictions.py ../1PooledPredictions/xCell_PBMC1NormMix_default.tsv ../../TrueProportions/TruePropsPBMC1.tsv > ReformattedPredictions/xCell_PBMC1NormMix_default.tsv
python A_FormatPredictions.py ../1PooledPredictions/AbsCIBERSORT_PBMC2NormMix_LM22-Full.tsv ../../TrueProportions/TruePropsPBMC2.tsv > ReformattedPredictions/AbsCIBERSORT_PBMC2NormMix_LM22-Full.tsv
python A_FormatPredictions.py ../1PooledPredictions/CIBERSORT_PBMC2NormMix_LM22-Full.tsv ../../TrueProportions/TruePropsPBMC2.tsv > ReformattedPredictions/CIBERSORT_PBMC2NormMix_LM22-Full.tsv
python A_FormatPredictions.py ../1PooledPredictions/DCQ_PBMC2NormMix_EPIC-BCIC.tsv ../../TrueProportions/TruePropsPBMC2.tsv > ReformattedPredictions/DCQ_PBMC2NormMix_EPIC-BCIC.tsv
python A_FormatPredictions.py ../1PooledPredictions/DeconRNASeq_PBMC2NormMix_LM22-Full.tsv ../../TrueProportions/TruePropsPBMC2.tsv > ReformattedPredictions/DeconRNASeq_PBMC2NormMix_LM22-Full.tsv
python A_FormatPredictions.py ../1PooledPredictions/EPIC_PBMC2NormMix_EPIC-BCIC.tsv ../../TrueProportions/TruePropsPBMC2.tsv > ReformattedPredictions/EPIC_PBMC2NormMix_EPIC-BCIC.tsv
python A_FormatPredictions.py ../1PooledPredictions/GEDIT_PBMC2NormMix_EPIC-BCIC.tsv ../../TrueProportions/TruePropsPBMC2.tsv > ReformattedPredictions/GEDIT_PBMC2NormMix_EPIC-BCIC.tsv
python A_FormatPredictions.py ../1PooledPredictions/MCP-counter_PBMC2NormMix_default.tsv ../../TrueProportions/TruePropsPBMC2.tsv > ReformattedPredictions/MCP-counter_PBMC2NormMix_default.tsv
python A_FormatPredictions.py ../1PooledPredictions/SaVanT_PBMC2NormMix_SkinSignaturesV1.tsv ../../TrueProportions/TruePropsPBMC2.tsv > ReformattedPredictions/SaVanT_PBMC2NormMix_SkinSignaturesV1.tsv
python A_FormatPredictions.py ../1PooledPredictions/dtangle_PBMC2NormMix_SkinSignaturesV1.tsv ../../TrueProportions/TruePropsPBMC2.tsv > ReformattedPredictions/dtangle_PBMC2NormMix_SkinSignaturesV1.tsv
python A_FormatPredictions.py ../1PooledPredictions/nnls_PBMC2NormMix_LM22-Full.tsv ../../TrueProportions/TruePropsPBMC2.tsv > ReformattedPredictions/nnls_PBMC2NormMix_LM22-Full.tsv
python A_FormatPredictions.py ../1PooledPredictions/quanTIseq_PBMC2NormMix_default.tsv ../../TrueProportions/TruePropsPBMC2.tsv > ReformattedPredictions/quanTIseq_PBMC2NormMix_default.tsv
python A_FormatPredictions.py ../1PooledPredictions/xCell_PBMC2NormMix_default.tsv ../../TrueProportions/TruePropsPBMC2.tsv > ReformattedPredictions/xCell_PBMC2NormMix_default.tsv
python A_FormatPredictions.py ../1PooledPredictions/AbsCIBERSORT_StromalNormMix_EPIC-TIC.tsv ../../TrueProportions/TruePropsStromal.tsv > ReformattedPredictions/AbsCIBERSORT_StromalNormMix_EPIC-TIC.tsv
python A_FormatPredictions.py ../1PooledPredictions/CIBERSORT_StromalNormMix_EPIC-TIC.tsv ../../TrueProportions/TruePropsStromal.tsv > ReformattedPredictions/CIBERSORT_StromalNormMix_EPIC-TIC.tsv
python A_FormatPredictions.py ../1PooledPredictions/DCQ_StromalNormMix_HPCA-Stromal.tsv ../../TrueProportions/TruePropsStromal.tsv > ReformattedPredictions/DCQ_StromalNormMix_HPCA-Stromal.tsv
python A_FormatPredictions.py ../1PooledPredictions/DeconRNASeq_StromalNormMix_SkinSignaturesV1.tsv ../../TrueProportions/TruePropsStromal.tsv > ReformattedPredictions/DeconRNASeq_StromalNormMix_SkinSignaturesV1.tsv
python A_FormatPredictions.py ../1PooledPredictions/EPIC_StromalNormMix_EPIC-BCIC.tsv ../../TrueProportions/TruePropsStromal.tsv > ReformattedPredictions/EPIC_StromalNormMix_EPIC-BCIC.tsv
python A_FormatPredictions.py ../1PooledPredictions/GEDIT_StromalNormMix_HPCA-Stromal.tsv ../../TrueProportions/TruePropsStromal.tsv > ReformattedPredictions/GEDIT_StromalNormMix_HPCA-Stromal.tsv
python A_FormatPredictions.py ../1PooledPredictions/MCP-counter_StromalNormMix_default.tsv ../../TrueProportions/TruePropsStromal.tsv > ReformattedPredictions/MCP-counter_StromalNormMix_default.tsv
python A_FormatPredictions.py ../1PooledPredictions/SaVanT_StromalNormMix_HPCA-Stromal.tsv ../../TrueProportions/TruePropsStromal.tsv > ReformattedPredictions/SaVanT_StromalNormMix_HPCA-Stromal.tsv
python A_FormatPredictions.py ../1PooledPredictions/dtangle_StromalNormMix_BlueCodeV1.tsv ../../TrueProportions/TruePropsStromal.tsv > ReformattedPredictions/dtangle_StromalNormMix_BlueCodeV1.tsv
python A_FormatPredictions.py ../1PooledPredictions/nnls_StromalNormMix_LM22-Full.tsv ../../TrueProportions/TruePropsStromal.tsv > ReformattedPredictions/nnls_StromalNormMix_LM22-Full.tsv
python A_FormatPredictions.py ../1PooledPredictions/quanTIseq_StromalNormMix_default.tsv ../../TrueProportions/TruePropsStromal.tsv > ReformattedPredictions/quanTIseq_StromalNormMix_default.tsv
python A_FormatPredictions.py ../1PooledPredictions/xCell_StromalNormMix_default.tsv ../../TrueProportions/TruePropsStromal.tsv > ReformattedPredictions/xCell_StromalNormMix_default.tsv
python B_FormatFram.py ../1PooledPredictions/AbsCIBERSORT_Fram_HPCA-Blood.tsv ../../TrueProportions/TruePropsFram.tsv > ReformattedPredictions/AbsCIBERSORT_Fram_HPCA-Blood.tsv
python B_FormatFram.py ../1PooledPredictions/CIBERSORT_Fram_HPCA-Blood.tsv ../../TrueProportions/TruePropsFram.tsv > ReformattedPredictions/CIBERSORT_Fram_HPCA-Blood.tsv
python B_FormatFram.py ../1PooledPredictions/DCQ_Fram_BlueCodeV1.tsv ../../TrueProportions/TruePropsFram.tsv > ReformattedPredictions/DCQ_Fram_BlueCodeV1.tsv
python B_FormatFram.py ../1PooledPredictions/DeconRNASeq_Fram_SkinSignaturesV1.tsv ../../TrueProportions/TruePropsFram.tsv > ReformattedPredictions/DeconRNASeq_Fram_SkinSignaturesV1.tsv
python B_FormatFram.py ../1PooledPredictions/EPIC_Fram_SkinSignaturesV1.tsv ../../TrueProportions/TruePropsFram.tsv > ReformattedPredictions/EPIC_Fram_SkinSignaturesV1.tsv
python B_FormatFram.py ../1PooledPredictions/GEDIT_Fram_LM22-Full.tsv ../../TrueProportions/TruePropsFram.tsv > ReformattedPredictions/GEDIT_Fram_LM22-Full.tsv
python B_FormatFram.py ../1PooledPredictions/MCP-counter_Fram_default.tsv ../../TrueProportions/TruePropsFram.tsv > ReformattedPredictions/MCP-counter_Fram_default.tsv
python B_FormatFram.py ../1PooledPredictions/SaVanT_Fram_EPIC-BCIC.tsv ../../TrueProportions/TruePropsFram.tsv > ReformattedPredictions/SaVanT_Fram_EPIC-BCIC.tsv
python B_FormatFram.py ../1PooledPredictions/dtangle_Fram_LM22-Full.tsv ../../TrueProportions/TruePropsFram.tsv > ReformattedPredictions/dtangle_Fram_LM22-Full.tsv
python B_FormatFram.py ../1PooledPredictions/nnls_Fram_SkinSignaturesV1.tsv ../../TrueProportions/TruePropsFram.tsv > ReformattedPredictions/nnls_Fram_SkinSignaturesV1.tsv
python B_FormatFram.py ../1PooledPredictions/quanTIseq_Fram_default.tsv ../../TrueProportions/TruePropsFram.tsv > ReformattedPredictions/quanTIseq_Fram_default.tsv
python B_FormatFram.py ../1PooledPredictions/xCell_Fram_default.tsv ../../TrueProportions/TruePropsFram.tsv > ReformattedPredictions/xCell_Fram_default.tsv
