cp ../../Tools/DCQ/FinalPredictions/* PooledPredictions/
cp ../../Tools/GEDITv1.5/FinalPredictions/* PooledPredictions/
cp ../../Tools/dtangle/predictions/* PooledPredictions/
cp ../../Tools/DeconRNASeq/predictions/* PooledPredictions/
cp ../../Tools/EPIC/predictions/* PooledPredictions/
cp ../../Tools/MCP_Counter/predictions/* PooledPredictions/
cp ../../Tools/SaVanT/predictions/* PooledPredictions/
cp ../../Tools/xCell/predictions/* PooledPredictions/
cp ../../Tools/cibersort/predictions/* PooledPredictions/
