python B_NormFile.py ../2ReformatPredictions/ReformattedPredictions/Cibersort_CellMixtures_10XImmune.tsv > NormedPredictions/Cibersort_CellMixtures_10XImmune.tsv
python B_NormFile.py ../2ReformatPredictions/ReformattedPredictions/Cibersort_CellMixtures_BlueCodeV1.tsv > NormedPredictions/Cibersort_CellMixtures_BlueCodeV1.tsv
python B_NormFile.py ../2ReformatPredictions/ReformattedPredictions/Cibersort_CellMixtures_BluePrint-Blood.tsv > NormedPredictions/Cibersort_CellMixtures_BluePrint-Blood.tsv
python B_NormFile.py ../2ReformatPredictions/ReformattedPredictions/Cibersort_CellMixtures_EPIC-BCIC.tsv > NormedPredictions/Cibersort_CellMixtures_EPIC-BCIC.tsv
python B_NormFile.py ../2ReformatPredictions/ReformattedPredictions/Cibersort_CellMixtures_EPIC-TIC.tsv > NormedPredictions/Cibersort_CellMixtures_EPIC-TIC.tsv
python B_NormFile.py ../2ReformatPredictions/ReformattedPredictions/Cibersort_CellMixtures_HPCA-Blood.tsv > NormedPredictions/Cibersort_CellMixtures_HPCA-Blood.tsv
python B_NormFile.py ../2ReformatPredictions/ReformattedPredictions/Cibersort_CellMixtures_HPCA-Stromal.tsv > NormedPredictions/Cibersort_CellMixtures_HPCA-Stromal.tsv
python B_NormFile.py ../2ReformatPredictions/ReformattedPredictions/Cibersort_CellMixtures_ImmunoStates-Blood.tsv > NormedPredictions/Cibersort_CellMixtures_ImmunoStates-Blood.tsv
python B_NormFile.py ../2ReformatPredictions/ReformattedPredictions/Cibersort_CellMixtures_ImmunoStates-Full.tsv > NormedPredictions/Cibersort_CellMixtures_ImmunoStates-Full.tsv
python B_NormFile.py ../2ReformatPredictions/ReformattedPredictions/Cibersort_CellMixtures_ImmunoStates-Stromal.tsv > NormedPredictions/Cibersort_CellMixtures_ImmunoStates-Stromal.tsv
python B_NormFile.py ../2ReformatPredictions/ReformattedPredictions/Cibersort_CellMixtures_LM22-Blood.tsv > NormedPredictions/Cibersort_CellMixtures_LM22-Blood.tsv
python B_NormFile.py ../2ReformatPredictions/ReformattedPredictions/Cibersort_CellMixtures_LM22-Full.tsv > NormedPredictions/Cibersort_CellMixtures_LM22-Full.tsv
python B_NormFile.py ../2ReformatPredictions/ReformattedPredictions/Cibersort_CellMixtures_LM22-Stromal.tsv > NormedPredictions/Cibersort_CellMixtures_LM22-Stromal.tsv
python B_NormFile.py ../2ReformatPredictions/ReformattedPredictions/Cibersort_CellMixtures_SkinSignaturesV1.tsv > NormedPredictions/Cibersort_CellMixtures_SkinSignaturesV1.tsv
python B_NormFile.py ../2ReformatPredictions/ReformattedPredictions/Cibersort_Fram_BluePrint-Blood.tsv > NormedPredictions/Cibersort_Fram_BluePrint-Blood.tsv
python B_NormFile.py ../2ReformatPredictions/ReformattedPredictions/Cibersort_PBMC1NormMix_10XImmune.tsv > NormedPredictions/Cibersort_PBMC1NormMix_10XImmune.tsv
python B_NormFile.py ../2ReformatPredictions/ReformattedPredictions/Cibersort_PBMC1NormMix_BlueCodeV1.tsv > NormedPredictions/Cibersort_PBMC1NormMix_BlueCodeV1.tsv
python B_NormFile.py ../2ReformatPredictions/ReformattedPredictions/Cibersort_PBMC1NormMix_EPIC-TIC.tsv > NormedPredictions/Cibersort_PBMC1NormMix_EPIC-TIC.tsv
python B_NormFile.py ../2ReformatPredictions/ReformattedPredictions/Cibersort_PBMC1NormMix_HPCA-Stromal.tsv > NormedPredictions/Cibersort_PBMC1NormMix_HPCA-Stromal.tsv
python B_NormFile.py ../2ReformatPredictions/ReformattedPredictions/Cibersort_PBMC1NormMix_ImmunoStates-Stromal.tsv > NormedPredictions/Cibersort_PBMC1NormMix_ImmunoStates-Stromal.tsv
python B_NormFile.py ../2ReformatPredictions/ReformattedPredictions/Cibersort_PBMC1NormMix_LM22-Stromal.tsv > NormedPredictions/Cibersort_PBMC1NormMix_LM22-Stromal.tsv
python B_NormFile.py ../2ReformatPredictions/ReformattedPredictions/Cibersort_PBMC1NormMix_SkinSignaturesV1.tsv > NormedPredictions/Cibersort_PBMC1NormMix_SkinSignaturesV1.tsv
python B_NormFile.py ../2ReformatPredictions/ReformattedPredictions/Cibersort_PBMC2NormMix_10XImmune.tsv > NormedPredictions/Cibersort_PBMC2NormMix_10XImmune.tsv
python B_NormFile.py ../2ReformatPredictions/ReformattedPredictions/Cibersort_PBMC2NormMix_BlueCodeV1.tsv > NormedPredictions/Cibersort_PBMC2NormMix_BlueCodeV1.tsv
python B_NormFile.py ../2ReformatPredictions/ReformattedPredictions/Cibersort_PBMC2NormMix_EPIC-TIC.tsv > NormedPredictions/Cibersort_PBMC2NormMix_EPIC-TIC.tsv
python B_NormFile.py ../2ReformatPredictions/ReformattedPredictions/Cibersort_PBMC2NormMix_HPCA-Stromal.tsv > NormedPredictions/Cibersort_PBMC2NormMix_HPCA-Stromal.tsv
python B_NormFile.py ../2ReformatPredictions/ReformattedPredictions/Cibersort_PBMC2NormMix_ImmunoStates-Stromal.tsv > NormedPredictions/Cibersort_PBMC2NormMix_ImmunoStates-Stromal.tsv
python B_NormFile.py ../2ReformatPredictions/ReformattedPredictions/Cibersort_PBMC2NormMix_LM22-Stromal.tsv > NormedPredictions/Cibersort_PBMC2NormMix_LM22-Stromal.tsv
python B_NormFile.py ../2ReformatPredictions/ReformattedPredictions/Cibersort_StromalNormMix_10XImmune.tsv > NormedPredictions/Cibersort_StromalNormMix_10XImmune.tsv
python B_NormFile.py ../2ReformatPredictions/ReformattedPredictions/Cibersort_StromalNormMix_BlueCodeV1.tsv > NormedPredictions/Cibersort_StromalNormMix_BlueCodeV1.tsv
python B_NormFile.py ../2ReformatPredictions/ReformattedPredictions/Cibersort_StromalNormMix_HPCA-Stromal.tsv > NormedPredictions/Cibersort_StromalNormMix_HPCA-Stromal.tsv
python B_NormFile.py ../2ReformatPredictions/ReformattedPredictions/Cibersort_StromalNormMix_SkinSignaturesV1.tsv > NormedPredictions/Cibersort_StromalNormMix_SkinSignaturesV1.tsv
python B_NormFile.py ../2ReformatPredictions/ReformattedPredictions/DCQ_CellMixtures_10XImmune.tsv > NormedPredictions/DCQ_CellMixtures_10XImmune.tsv
python B_NormFile.py ../2ReformatPredictions/ReformattedPredictions/DCQ_CellMixtures_BlueCodeV1.tsv > NormedPredictions/DCQ_CellMixtures_BlueCodeV1.tsv
python B_NormFile.py ../2ReformatPredictions/ReformattedPredictions/DCQ_CellMixtures_BluePrint-Blood.tsv > NormedPredictions/DCQ_CellMixtures_BluePrint-Blood.tsv
python B_NormFile.py ../2ReformatPredictions/ReformattedPredictions/DCQ_CellMixtures_EPIC-BCIC.tsv > NormedPredictions/DCQ_CellMixtures_EPIC-BCIC.tsv
python B_NormFile.py ../2ReformatPredictions/ReformattedPredictions/DCQ_CellMixtures_EPIC-TIC.tsv > NormedPredictions/DCQ_CellMixtures_EPIC-TIC.tsv
python B_NormFile.py ../2ReformatPredictions/ReformattedPredictions/DCQ_CellMixtures_HPCA-Blood.tsv > NormedPredictions/DCQ_CellMixtures_HPCA-Blood.tsv
python B_NormFile.py ../2ReformatPredictions/ReformattedPredictions/DCQ_CellMixtures_HPCA-Stromal.tsv > NormedPredictions/DCQ_CellMixtures_HPCA-Stromal.tsv
python B_NormFile.py ../2ReformatPredictions/ReformattedPredictions/DCQ_CellMixtures_ImmunoStates-Blood.tsv > NormedPredictions/DCQ_CellMixtures_ImmunoStates-Blood.tsv
python B_NormFile.py ../2ReformatPredictions/ReformattedPredictions/DCQ_CellMixtures_ImmunoStates-Full.tsv > NormedPredictions/DCQ_CellMixtures_ImmunoStates-Full.tsv
python B_NormFile.py ../2ReformatPredictions/ReformattedPredictions/DCQ_CellMixtures_ImmunoStates-Stromal.tsv > NormedPredictions/DCQ_CellMixtures_ImmunoStates-Stromal.tsv
python B_NormFile.py ../2ReformatPredictions/ReformattedPredictions/DCQ_CellMixtures_LM22-Blood.tsv > NormedPredictions/DCQ_CellMixtures_LM22-Blood.tsv
python B_NormFile.py ../2ReformatPredictions/ReformattedPredictions/DCQ_CellMixtures_LM22-Full.tsv > NormedPredictions/DCQ_CellMixtures_LM22-Full.tsv
python B_NormFile.py ../2ReformatPredictions/ReformattedPredictions/DCQ_CellMixtures_LM22-Stromal.tsv > NormedPredictions/DCQ_CellMixtures_LM22-Stromal.tsv
python B_NormFile.py ../2ReformatPredictions/ReformattedPredictions/DCQ_CellMixtures_SkinSignaturesV1.tsv > NormedPredictions/DCQ_CellMixtures_SkinSignaturesV1.tsv
python B_NormFile.py ../2ReformatPredictions/ReformattedPredictions/DCQ_Fram_10XImmune.tsv > NormedPredictions/DCQ_Fram_10XImmune.tsv
python B_NormFile.py ../2ReformatPredictions/ReformattedPredictions/DCQ_Fram_BlueCodeV1.tsv > NormedPredictions/DCQ_Fram_BlueCodeV1.tsv
python B_NormFile.py ../2ReformatPredictions/ReformattedPredictions/DCQ_Fram_BluePrint-Blood.tsv > NormedPredictions/DCQ_Fram_BluePrint-Blood.tsv
python B_NormFile.py ../2ReformatPredictions/ReformattedPredictions/DCQ_Fram_EPIC-BCIC.tsv > NormedPredictions/DCQ_Fram_EPIC-BCIC.tsv
python B_NormFile.py ../2ReformatPredictions/ReformattedPredictions/DCQ_Fram_EPIC-TIC.tsv > NormedPredictions/DCQ_Fram_EPIC-TIC.tsv
python B_NormFile.py ../2ReformatPredictions/ReformattedPredictions/DCQ_Fram_HPCA-Blood.tsv > NormedPredictions/DCQ_Fram_HPCA-Blood.tsv
python B_NormFile.py ../2ReformatPredictions/ReformattedPredictions/DCQ_Fram_HPCA-Stromal.tsv > NormedPredictions/DCQ_Fram_HPCA-Stromal.tsv
python B_NormFile.py ../2ReformatPredictions/ReformattedPredictions/DCQ_Fram_ImmunoStates-Blood.tsv > NormedPredictions/DCQ_Fram_ImmunoStates-Blood.tsv
python B_NormFile.py ../2ReformatPredictions/ReformattedPredictions/DCQ_Fram_ImmunoStates-Full.tsv > NormedPredictions/DCQ_Fram_ImmunoStates-Full.tsv
python B_NormFile.py ../2ReformatPredictions/ReformattedPredictions/DCQ_Fram_ImmunoStates-Stromal.tsv > NormedPredictions/DCQ_Fram_ImmunoStates-Stromal.tsv
python B_NormFile.py ../2ReformatPredictions/ReformattedPredictions/DCQ_Fram_LM22-Blood.tsv > NormedPredictions/DCQ_Fram_LM22-Blood.tsv
python B_NormFile.py ../2ReformatPredictions/ReformattedPredictions/DCQ_Fram_LM22-Full.tsv > NormedPredictions/DCQ_Fram_LM22-Full.tsv
python B_NormFile.py ../2ReformatPredictions/ReformattedPredictions/DCQ_Fram_LM22-Stromal.tsv > NormedPredictions/DCQ_Fram_LM22-Stromal.tsv
python B_NormFile.py ../2ReformatPredictions/ReformattedPredictions/DCQ_Fram_SkinSignaturesV1.tsv > NormedPredictions/DCQ_Fram_SkinSignaturesV1.tsv
python B_NormFile.py ../2ReformatPredictions/ReformattedPredictions/DCQ_PBMC1NormMix_10XImmune.tsv > NormedPredictions/DCQ_PBMC1NormMix_10XImmune.tsv
python B_NormFile.py ../2ReformatPredictions/ReformattedPredictions/DCQ_PBMC1NormMix_BlueCodeV1.tsv > NormedPredictions/DCQ_PBMC1NormMix_BlueCodeV1.tsv
python B_NormFile.py ../2ReformatPredictions/ReformattedPredictions/DCQ_PBMC1NormMix_BluePrint-Blood.tsv > NormedPredictions/DCQ_PBMC1NormMix_BluePrint-Blood.tsv
python B_NormFile.py ../2ReformatPredictions/ReformattedPredictions/DCQ_PBMC1NormMix_EPIC-BCIC.tsv > NormedPredictions/DCQ_PBMC1NormMix_EPIC-BCIC.tsv
python B_NormFile.py ../2ReformatPredictions/ReformattedPredictions/DCQ_PBMC1NormMix_EPIC-TIC.tsv > NormedPredictions/DCQ_PBMC1NormMix_EPIC-TIC.tsv
python B_NormFile.py ../2ReformatPredictions/ReformattedPredictions/DCQ_PBMC1NormMix_HPCA-Blood.tsv > NormedPredictions/DCQ_PBMC1NormMix_HPCA-Blood.tsv
python B_NormFile.py ../2ReformatPredictions/ReformattedPredictions/DCQ_PBMC1NormMix_HPCA-Stromal.tsv > NormedPredictions/DCQ_PBMC1NormMix_HPCA-Stromal.tsv
python B_NormFile.py ../2ReformatPredictions/ReformattedPredictions/DCQ_PBMC1NormMix_ImmunoStates-Blood.tsv > NormedPredictions/DCQ_PBMC1NormMix_ImmunoStates-Blood.tsv
python B_NormFile.py ../2ReformatPredictions/ReformattedPredictions/DCQ_PBMC1NormMix_ImmunoStates-Full.tsv > NormedPredictions/DCQ_PBMC1NormMix_ImmunoStates-Full.tsv
python B_NormFile.py ../2ReformatPredictions/ReformattedPredictions/DCQ_PBMC1NormMix_ImmunoStates-Stromal.tsv > NormedPredictions/DCQ_PBMC1NormMix_ImmunoStates-Stromal.tsv
python B_NormFile.py ../2ReformatPredictions/ReformattedPredictions/DCQ_PBMC1NormMix_LM22-Blood.tsv > NormedPredictions/DCQ_PBMC1NormMix_LM22-Blood.tsv
python B_NormFile.py ../2ReformatPredictions/ReformattedPredictions/DCQ_PBMC1NormMix_LM22-Full.tsv > NormedPredictions/DCQ_PBMC1NormMix_LM22-Full.tsv
python B_NormFile.py ../2ReformatPredictions/ReformattedPredictions/DCQ_PBMC1NormMix_LM22-Stromal.tsv > NormedPredictions/DCQ_PBMC1NormMix_LM22-Stromal.tsv
python B_NormFile.py ../2ReformatPredictions/ReformattedPredictions/DCQ_PBMC1NormMix_SkinSignaturesV1.tsv > NormedPredictions/DCQ_PBMC1NormMix_SkinSignaturesV1.tsv
python B_NormFile.py ../2ReformatPredictions/ReformattedPredictions/DCQ_PBMC2NormMix_10XImmune.tsv > NormedPredictions/DCQ_PBMC2NormMix_10XImmune.tsv
python B_NormFile.py ../2ReformatPredictions/ReformattedPredictions/DCQ_PBMC2NormMix_BlueCodeV1.tsv > NormedPredictions/DCQ_PBMC2NormMix_BlueCodeV1.tsv
python B_NormFile.py ../2ReformatPredictions/ReformattedPredictions/DCQ_PBMC2NormMix_BluePrint-Blood.tsv > NormedPredictions/DCQ_PBMC2NormMix_BluePrint-Blood.tsv
python B_NormFile.py ../2ReformatPredictions/ReformattedPredictions/DCQ_PBMC2NormMix_EPIC-BCIC.tsv > NormedPredictions/DCQ_PBMC2NormMix_EPIC-BCIC.tsv
python B_NormFile.py ../2ReformatPredictions/ReformattedPredictions/DCQ_PBMC2NormMix_EPIC-TIC.tsv > NormedPredictions/DCQ_PBMC2NormMix_EPIC-TIC.tsv
python B_NormFile.py ../2ReformatPredictions/ReformattedPredictions/DCQ_PBMC2NormMix_HPCA-Blood.tsv > NormedPredictions/DCQ_PBMC2NormMix_HPCA-Blood.tsv
python B_NormFile.py ../2ReformatPredictions/ReformattedPredictions/DCQ_PBMC2NormMix_HPCA-Stromal.tsv > NormedPredictions/DCQ_PBMC2NormMix_HPCA-Stromal.tsv
python B_NormFile.py ../2ReformatPredictions/ReformattedPredictions/DCQ_PBMC2NormMix_ImmunoStates-Blood.tsv > NormedPredictions/DCQ_PBMC2NormMix_ImmunoStates-Blood.tsv
python B_NormFile.py ../2ReformatPredictions/ReformattedPredictions/DCQ_PBMC2NormMix_ImmunoStates-Full.tsv > NormedPredictions/DCQ_PBMC2NormMix_ImmunoStates-Full.tsv
python B_NormFile.py ../2ReformatPredictions/ReformattedPredictions/DCQ_PBMC2NormMix_ImmunoStates-Stromal.tsv > NormedPredictions/DCQ_PBMC2NormMix_ImmunoStates-Stromal.tsv
python B_NormFile.py ../2ReformatPredictions/ReformattedPredictions/DCQ_PBMC2NormMix_LM22-Blood.tsv > NormedPredictions/DCQ_PBMC2NormMix_LM22-Blood.tsv
python B_NormFile.py ../2ReformatPredictions/ReformattedPredictions/DCQ_PBMC2NormMix_LM22-Full.tsv > NormedPredictions/DCQ_PBMC2NormMix_LM22-Full.tsv
python B_NormFile.py ../2ReformatPredictions/ReformattedPredictions/DCQ_PBMC2NormMix_LM22-Stromal.tsv > NormedPredictions/DCQ_PBMC2NormMix_LM22-Stromal.tsv
python B_NormFile.py ../2ReformatPredictions/ReformattedPredictions/DCQ_PBMC2NormMix_SkinSignaturesV1.tsv > NormedPredictions/DCQ_PBMC2NormMix_SkinSignaturesV1.tsv
python B_NormFile.py ../2ReformatPredictions/ReformattedPredictions/DCQ_StromalNormMix_10XImmune.tsv > NormedPredictions/DCQ_StromalNormMix_10XImmune.tsv
python B_NormFile.py ../2ReformatPredictions/ReformattedPredictions/DCQ_StromalNormMix_BlueCodeV1.tsv > NormedPredictions/DCQ_StromalNormMix_BlueCodeV1.tsv
python B_NormFile.py ../2ReformatPredictions/ReformattedPredictions/DCQ_StromalNormMix_BluePrint-Blood.tsv > NormedPredictions/DCQ_StromalNormMix_BluePrint-Blood.tsv
python B_NormFile.py ../2ReformatPredictions/ReformattedPredictions/DCQ_StromalNormMix_EPIC-BCIC.tsv > NormedPredictions/DCQ_StromalNormMix_EPIC-BCIC.tsv
python B_NormFile.py ../2ReformatPredictions/ReformattedPredictions/DCQ_StromalNormMix_EPIC-TIC.tsv > NormedPredictions/DCQ_StromalNormMix_EPIC-TIC.tsv
python B_NormFile.py ../2ReformatPredictions/ReformattedPredictions/DCQ_StromalNormMix_HPCA-Blood.tsv > NormedPredictions/DCQ_StromalNormMix_HPCA-Blood.tsv
python B_NormFile.py ../2ReformatPredictions/ReformattedPredictions/DCQ_StromalNormMix_HPCA-Stromal.tsv > NormedPredictions/DCQ_StromalNormMix_HPCA-Stromal.tsv
python B_NormFile.py ../2ReformatPredictions/ReformattedPredictions/DCQ_StromalNormMix_ImmunoStates-Blood.tsv > NormedPredictions/DCQ_StromalNormMix_ImmunoStates-Blood.tsv
python B_NormFile.py ../2ReformatPredictions/ReformattedPredictions/DCQ_StromalNormMix_ImmunoStates-Full.tsv > NormedPredictions/DCQ_StromalNormMix_ImmunoStates-Full.tsv
python B_NormFile.py ../2ReformatPredictions/ReformattedPredictions/DCQ_StromalNormMix_ImmunoStates-Stromal.tsv > NormedPredictions/DCQ_StromalNormMix_ImmunoStates-Stromal.tsv
python B_NormFile.py ../2ReformatPredictions/ReformattedPredictions/DCQ_StromalNormMix_LM22-Blood.tsv > NormedPredictions/DCQ_StromalNormMix_LM22-Blood.tsv
python B_NormFile.py ../2ReformatPredictions/ReformattedPredictions/DCQ_StromalNormMix_LM22-Full.tsv > NormedPredictions/DCQ_StromalNormMix_LM22-Full.tsv
python B_NormFile.py ../2ReformatPredictions/ReformattedPredictions/DCQ_StromalNormMix_LM22-Stromal.tsv > NormedPredictions/DCQ_StromalNormMix_LM22-Stromal.tsv
python B_NormFile.py ../2ReformatPredictions/ReformattedPredictions/DCQ_StromalNormMix_SkinSignaturesV1.tsv > NormedPredictions/DCQ_StromalNormMix_SkinSignaturesV1.tsv
python B_NormFile.py ../2ReformatPredictions/ReformattedPredictions/Decon_CellMixtures_10XImmune.tsv > NormedPredictions/Decon_CellMixtures_10XImmune.tsv
python B_NormFile.py ../2ReformatPredictions/ReformattedPredictions/Decon_CellMixtures_BlueCodeV1.tsv > NormedPredictions/Decon_CellMixtures_BlueCodeV1.tsv
python B_NormFile.py ../2ReformatPredictions/ReformattedPredictions/Decon_CellMixtures_BluePrint-Blood.tsv > NormedPredictions/Decon_CellMixtures_BluePrint-Blood.tsv
python B_NormFile.py ../2ReformatPredictions/ReformattedPredictions/Decon_CellMixtures_EPIC-BCIC.tsv > NormedPredictions/Decon_CellMixtures_EPIC-BCIC.tsv
python B_NormFile.py ../2ReformatPredictions/ReformattedPredictions/Decon_CellMixtures_EPIC-TIC.tsv > NormedPredictions/Decon_CellMixtures_EPIC-TIC.tsv
python B_NormFile.py ../2ReformatPredictions/ReformattedPredictions/Decon_CellMixtures_HPCA-Blood.tsv > NormedPredictions/Decon_CellMixtures_HPCA-Blood.tsv
python B_NormFile.py ../2ReformatPredictions/ReformattedPredictions/Decon_CellMixtures_HPCA-Stromal.tsv > NormedPredictions/Decon_CellMixtures_HPCA-Stromal.tsv
python B_NormFile.py ../2ReformatPredictions/ReformattedPredictions/Decon_CellMixtures_ImmunoStates-Blood.tsv > NormedPredictions/Decon_CellMixtures_ImmunoStates-Blood.tsv
python B_NormFile.py ../2ReformatPredictions/ReformattedPredictions/Decon_CellMixtures_ImmunoStates-Full.tsv > NormedPredictions/Decon_CellMixtures_ImmunoStates-Full.tsv
python B_NormFile.py ../2ReformatPredictions/ReformattedPredictions/Decon_CellMixtures_ImmunoStates-Stromal.tsv > NormedPredictions/Decon_CellMixtures_ImmunoStates-Stromal.tsv
python B_NormFile.py ../2ReformatPredictions/ReformattedPredictions/Decon_CellMixtures_LM22-Blood.tsv > NormedPredictions/Decon_CellMixtures_LM22-Blood.tsv
python B_NormFile.py ../2ReformatPredictions/ReformattedPredictions/Decon_CellMixtures_LM22-Full.tsv > NormedPredictions/Decon_CellMixtures_LM22-Full.tsv
python B_NormFile.py ../2ReformatPredictions/ReformattedPredictions/Decon_CellMixtures_LM22-Stromal.tsv > NormedPredictions/Decon_CellMixtures_LM22-Stromal.tsv
python B_NormFile.py ../2ReformatPredictions/ReformattedPredictions/Decon_CellMixtures_SkinSignaturesV1.tsv > NormedPredictions/Decon_CellMixtures_SkinSignaturesV1.tsv
python B_NormFile.py ../2ReformatPredictions/ReformattedPredictions/Decon_Fram_10XImmune.tsv > NormedPredictions/Decon_Fram_10XImmune.tsv
python B_NormFile.py ../2ReformatPredictions/ReformattedPredictions/Decon_Fram_BlueCodeV1.tsv > NormedPredictions/Decon_Fram_BlueCodeV1.tsv
python B_NormFile.py ../2ReformatPredictions/ReformattedPredictions/Decon_Fram_BluePrint-Blood.tsv > NormedPredictions/Decon_Fram_BluePrint-Blood.tsv
python B_NormFile.py ../2ReformatPredictions/ReformattedPredictions/Decon_Fram_EPIC-BCIC.tsv > NormedPredictions/Decon_Fram_EPIC-BCIC.tsv
python B_NormFile.py ../2ReformatPredictions/ReformattedPredictions/Decon_Fram_EPIC-TIC.tsv > NormedPredictions/Decon_Fram_EPIC-TIC.tsv
python B_NormFile.py ../2ReformatPredictions/ReformattedPredictions/Decon_Fram_HPCA-Blood.tsv > NormedPredictions/Decon_Fram_HPCA-Blood.tsv
python B_NormFile.py ../2ReformatPredictions/ReformattedPredictions/Decon_Fram_HPCA-Stromal.tsv > NormedPredictions/Decon_Fram_HPCA-Stromal.tsv
python B_NormFile.py ../2ReformatPredictions/ReformattedPredictions/Decon_Fram_ImmunoStates-Blood.tsv > NormedPredictions/Decon_Fram_ImmunoStates-Blood.tsv
python B_NormFile.py ../2ReformatPredictions/ReformattedPredictions/Decon_Fram_ImmunoStates-Full.tsv > NormedPredictions/Decon_Fram_ImmunoStates-Full.tsv
python B_NormFile.py ../2ReformatPredictions/ReformattedPredictions/Decon_Fram_ImmunoStates-Stromal.tsv > NormedPredictions/Decon_Fram_ImmunoStates-Stromal.tsv
python B_NormFile.py ../2ReformatPredictions/ReformattedPredictions/Decon_Fram_LM22-Blood.tsv > NormedPredictions/Decon_Fram_LM22-Blood.tsv
python B_NormFile.py ../2ReformatPredictions/ReformattedPredictions/Decon_Fram_LM22-Full.tsv > NormedPredictions/Decon_Fram_LM22-Full.tsv
python B_NormFile.py ../2ReformatPredictions/ReformattedPredictions/Decon_Fram_LM22-Stromal.tsv > NormedPredictions/Decon_Fram_LM22-Stromal.tsv
python B_NormFile.py ../2ReformatPredictions/ReformattedPredictions/Decon_Fram_SkinSignaturesV1.tsv > NormedPredictions/Decon_Fram_SkinSignaturesV1.tsv
python B_NormFile.py ../2ReformatPredictions/ReformattedPredictions/Decon_PBMC1NormMix_10XImmune.tsv > NormedPredictions/Decon_PBMC1NormMix_10XImmune.tsv
python B_NormFile.py ../2ReformatPredictions/ReformattedPredictions/Decon_PBMC1NormMix_BlueCodeV1.tsv > NormedPredictions/Decon_PBMC1NormMix_BlueCodeV1.tsv
python B_NormFile.py ../2ReformatPredictions/ReformattedPredictions/Decon_PBMC1NormMix_BluePrint-Blood.tsv > NormedPredictions/Decon_PBMC1NormMix_BluePrint-Blood.tsv
python B_NormFile.py ../2ReformatPredictions/ReformattedPredictions/Decon_PBMC1NormMix_EPIC-BCIC.tsv > NormedPredictions/Decon_PBMC1NormMix_EPIC-BCIC.tsv
python B_NormFile.py ../2ReformatPredictions/ReformattedPredictions/Decon_PBMC1NormMix_EPIC-TIC.tsv > NormedPredictions/Decon_PBMC1NormMix_EPIC-TIC.tsv
python B_NormFile.py ../2ReformatPredictions/ReformattedPredictions/Decon_PBMC1NormMix_HPCA-Blood.tsv > NormedPredictions/Decon_PBMC1NormMix_HPCA-Blood.tsv
python B_NormFile.py ../2ReformatPredictions/ReformattedPredictions/Decon_PBMC1NormMix_HPCA-Stromal.tsv > NormedPredictions/Decon_PBMC1NormMix_HPCA-Stromal.tsv
python B_NormFile.py ../2ReformatPredictions/ReformattedPredictions/Decon_PBMC1NormMix_ImmunoStates-Blood.tsv > NormedPredictions/Decon_PBMC1NormMix_ImmunoStates-Blood.tsv
python B_NormFile.py ../2ReformatPredictions/ReformattedPredictions/Decon_PBMC1NormMix_ImmunoStates-Full.tsv > NormedPredictions/Decon_PBMC1NormMix_ImmunoStates-Full.tsv
python B_NormFile.py ../2ReformatPredictions/ReformattedPredictions/Decon_PBMC1NormMix_ImmunoStates-Stromal.tsv > NormedPredictions/Decon_PBMC1NormMix_ImmunoStates-Stromal.tsv
python B_NormFile.py ../2ReformatPredictions/ReformattedPredictions/Decon_PBMC1NormMix_LM22-Blood.tsv > NormedPredictions/Decon_PBMC1NormMix_LM22-Blood.tsv
python B_NormFile.py ../2ReformatPredictions/ReformattedPredictions/Decon_PBMC1NormMix_LM22-Full.tsv > NormedPredictions/Decon_PBMC1NormMix_LM22-Full.tsv
python B_NormFile.py ../2ReformatPredictions/ReformattedPredictions/Decon_PBMC1NormMix_LM22-Stromal.tsv > NormedPredictions/Decon_PBMC1NormMix_LM22-Stromal.tsv
python B_NormFile.py ../2ReformatPredictions/ReformattedPredictions/Decon_PBMC1NormMix_SkinSignaturesV1.tsv > NormedPredictions/Decon_PBMC1NormMix_SkinSignaturesV1.tsv
python B_NormFile.py ../2ReformatPredictions/ReformattedPredictions/Decon_PBMC2NormMix_10XImmune.tsv > NormedPredictions/Decon_PBMC2NormMix_10XImmune.tsv
python B_NormFile.py ../2ReformatPredictions/ReformattedPredictions/Decon_PBMC2NormMix_BlueCodeV1.tsv > NormedPredictions/Decon_PBMC2NormMix_BlueCodeV1.tsv
python B_NormFile.py ../2ReformatPredictions/ReformattedPredictions/Decon_PBMC2NormMix_BluePrint-Blood.tsv > NormedPredictions/Decon_PBMC2NormMix_BluePrint-Blood.tsv
python B_NormFile.py ../2ReformatPredictions/ReformattedPredictions/Decon_PBMC2NormMix_EPIC-BCIC.tsv > NormedPredictions/Decon_PBMC2NormMix_EPIC-BCIC.tsv
python B_NormFile.py ../2ReformatPredictions/ReformattedPredictions/Decon_PBMC2NormMix_EPIC-TIC.tsv > NormedPredictions/Decon_PBMC2NormMix_EPIC-TIC.tsv
python B_NormFile.py ../2ReformatPredictions/ReformattedPredictions/Decon_PBMC2NormMix_HPCA-Blood.tsv > NormedPredictions/Decon_PBMC2NormMix_HPCA-Blood.tsv
python B_NormFile.py ../2ReformatPredictions/ReformattedPredictions/Decon_PBMC2NormMix_HPCA-Stromal.tsv > NormedPredictions/Decon_PBMC2NormMix_HPCA-Stromal.tsv
python B_NormFile.py ../2ReformatPredictions/ReformattedPredictions/Decon_PBMC2NormMix_ImmunoStates-Blood.tsv > NormedPredictions/Decon_PBMC2NormMix_ImmunoStates-Blood.tsv
python B_NormFile.py ../2ReformatPredictions/ReformattedPredictions/Decon_PBMC2NormMix_ImmunoStates-Full.tsv > NormedPredictions/Decon_PBMC2NormMix_ImmunoStates-Full.tsv
python B_NormFile.py ../2ReformatPredictions/ReformattedPredictions/Decon_PBMC2NormMix_ImmunoStates-Stromal.tsv > NormedPredictions/Decon_PBMC2NormMix_ImmunoStates-Stromal.tsv
python B_NormFile.py ../2ReformatPredictions/ReformattedPredictions/Decon_PBMC2NormMix_LM22-Blood.tsv > NormedPredictions/Decon_PBMC2NormMix_LM22-Blood.tsv
python B_NormFile.py ../2ReformatPredictions/ReformattedPredictions/Decon_PBMC2NormMix_LM22-Full.tsv > NormedPredictions/Decon_PBMC2NormMix_LM22-Full.tsv
python B_NormFile.py ../2ReformatPredictions/ReformattedPredictions/Decon_PBMC2NormMix_LM22-Stromal.tsv > NormedPredictions/Decon_PBMC2NormMix_LM22-Stromal.tsv
python B_NormFile.py ../2ReformatPredictions/ReformattedPredictions/Decon_PBMC2NormMix_SkinSignaturesV1.tsv > NormedPredictions/Decon_PBMC2NormMix_SkinSignaturesV1.tsv
python B_NormFile.py ../2ReformatPredictions/ReformattedPredictions/Decon_StromalNormMix_10XImmune.tsv > NormedPredictions/Decon_StromalNormMix_10XImmune.tsv
python B_NormFile.py ../2ReformatPredictions/ReformattedPredictions/Decon_StromalNormMix_BlueCodeV1.tsv > NormedPredictions/Decon_StromalNormMix_BlueCodeV1.tsv
python B_NormFile.py ../2ReformatPredictions/ReformattedPredictions/Decon_StromalNormMix_BluePrint-Blood.tsv > NormedPredictions/Decon_StromalNormMix_BluePrint-Blood.tsv
python B_NormFile.py ../2ReformatPredictions/ReformattedPredictions/Decon_StromalNormMix_EPIC-BCIC.tsv > NormedPredictions/Decon_StromalNormMix_EPIC-BCIC.tsv
python B_NormFile.py ../2ReformatPredictions/ReformattedPredictions/Decon_StromalNormMix_EPIC-TIC.tsv > NormedPredictions/Decon_StromalNormMix_EPIC-TIC.tsv
python B_NormFile.py ../2ReformatPredictions/ReformattedPredictions/Decon_StromalNormMix_HPCA-Blood.tsv > NormedPredictions/Decon_StromalNormMix_HPCA-Blood.tsv
python B_NormFile.py ../2ReformatPredictions/ReformattedPredictions/Decon_StromalNormMix_HPCA-Stromal.tsv > NormedPredictions/Decon_StromalNormMix_HPCA-Stromal.tsv
python B_NormFile.py ../2ReformatPredictions/ReformattedPredictions/Decon_StromalNormMix_ImmunoStates-Blood.tsv > NormedPredictions/Decon_StromalNormMix_ImmunoStates-Blood.tsv
python B_NormFile.py ../2ReformatPredictions/ReformattedPredictions/Decon_StromalNormMix_ImmunoStates-Full.tsv > NormedPredictions/Decon_StromalNormMix_ImmunoStates-Full.tsv
python B_NormFile.py ../2ReformatPredictions/ReformattedPredictions/Decon_StromalNormMix_ImmunoStates-Stromal.tsv > NormedPredictions/Decon_StromalNormMix_ImmunoStates-Stromal.tsv
python B_NormFile.py ../2ReformatPredictions/ReformattedPredictions/Decon_StromalNormMix_LM22-Blood.tsv > NormedPredictions/Decon_StromalNormMix_LM22-Blood.tsv
python B_NormFile.py ../2ReformatPredictions/ReformattedPredictions/Decon_StromalNormMix_LM22-Full.tsv > NormedPredictions/Decon_StromalNormMix_LM22-Full.tsv
python B_NormFile.py ../2ReformatPredictions/ReformattedPredictions/Decon_StromalNormMix_LM22-Stromal.tsv > NormedPredictions/Decon_StromalNormMix_LM22-Stromal.tsv
python B_NormFile.py ../2ReformatPredictions/ReformattedPredictions/Decon_StromalNormMix_SkinSignaturesV1.tsv > NormedPredictions/Decon_StromalNormMix_SkinSignaturesV1.tsv
python B_NormFile.py ../2ReformatPredictions/ReformattedPredictions/EPIC_CellMixtures_BluePrint-Blood.tsv > NormedPredictions/EPIC_CellMixtures_BluePrint-Blood.tsv
python B_NormFile.py ../2ReformatPredictions/ReformattedPredictions/EPIC_CellMixtures_EPIC-BCIC.tsv > NormedPredictions/EPIC_CellMixtures_EPIC-BCIC.tsv
python B_NormFile.py ../2ReformatPredictions/ReformattedPredictions/EPIC_CellMixtures_HPCA-Blood.tsv > NormedPredictions/EPIC_CellMixtures_HPCA-Blood.tsv
python B_NormFile.py ../2ReformatPredictions/ReformattedPredictions/EPIC_CellMixtures_ImmunoStates-Blood.tsv > NormedPredictions/EPIC_CellMixtures_ImmunoStates-Blood.tsv
python B_NormFile.py ../2ReformatPredictions/ReformattedPredictions/EPIC_CellMixtures_ImmunoStates-Full.tsv > NormedPredictions/EPIC_CellMixtures_ImmunoStates-Full.tsv
python B_NormFile.py ../2ReformatPredictions/ReformattedPredictions/EPIC_CellMixtures_LM22-Blood.tsv > NormedPredictions/EPIC_CellMixtures_LM22-Blood.tsv
python B_NormFile.py ../2ReformatPredictions/ReformattedPredictions/EPIC_CellMixtures_LM22-Full.tsv > NormedPredictions/EPIC_CellMixtures_LM22-Full.tsv
python B_NormFile.py ../2ReformatPredictions/ReformattedPredictions/EPIC_PBMC1NormMix_BluePrint-Blood.tsv > NormedPredictions/EPIC_PBMC1NormMix_BluePrint-Blood.tsv
python B_NormFile.py ../2ReformatPredictions/ReformattedPredictions/EPIC_PBMC1NormMix_EPIC-BCIC.tsv > NormedPredictions/EPIC_PBMC1NormMix_EPIC-BCIC.tsv
python B_NormFile.py ../2ReformatPredictions/ReformattedPredictions/EPIC_PBMC1NormMix_HPCA-Blood.tsv > NormedPredictions/EPIC_PBMC1NormMix_HPCA-Blood.tsv
python B_NormFile.py ../2ReformatPredictions/ReformattedPredictions/EPIC_PBMC1NormMix_ImmunoStates-Blood.tsv > NormedPredictions/EPIC_PBMC1NormMix_ImmunoStates-Blood.tsv
python B_NormFile.py ../2ReformatPredictions/ReformattedPredictions/EPIC_PBMC1NormMix_ImmunoStates-Full.tsv > NormedPredictions/EPIC_PBMC1NormMix_ImmunoStates-Full.tsv
python B_NormFile.py ../2ReformatPredictions/ReformattedPredictions/EPIC_PBMC1NormMix_LM22-Blood.tsv > NormedPredictions/EPIC_PBMC1NormMix_LM22-Blood.tsv
python B_NormFile.py ../2ReformatPredictions/ReformattedPredictions/EPIC_PBMC1NormMix_LM22-Full.tsv > NormedPredictions/EPIC_PBMC1NormMix_LM22-Full.tsv
python B_NormFile.py ../2ReformatPredictions/ReformattedPredictions/EPIC_PBMC2NormMix_BluePrint-Blood.tsv > NormedPredictions/EPIC_PBMC2NormMix_BluePrint-Blood.tsv
python B_NormFile.py ../2ReformatPredictions/ReformattedPredictions/EPIC_PBMC2NormMix_EPIC-BCIC.tsv > NormedPredictions/EPIC_PBMC2NormMix_EPIC-BCIC.tsv
python B_NormFile.py ../2ReformatPredictions/ReformattedPredictions/EPIC_PBMC2NormMix_HPCA-Blood.tsv > NormedPredictions/EPIC_PBMC2NormMix_HPCA-Blood.tsv
python B_NormFile.py ../2ReformatPredictions/ReformattedPredictions/EPIC_PBMC2NormMix_ImmunoStates-Blood.tsv > NormedPredictions/EPIC_PBMC2NormMix_ImmunoStates-Blood.tsv
python B_NormFile.py ../2ReformatPredictions/ReformattedPredictions/EPIC_PBMC2NormMix_ImmunoStates-Full.tsv > NormedPredictions/EPIC_PBMC2NormMix_ImmunoStates-Full.tsv
python B_NormFile.py ../2ReformatPredictions/ReformattedPredictions/EPIC_PBMC2NormMix_LM22-Blood.tsv > NormedPredictions/EPIC_PBMC2NormMix_LM22-Blood.tsv
python B_NormFile.py ../2ReformatPredictions/ReformattedPredictions/EPIC_PBMC2NormMix_LM22-Full.tsv > NormedPredictions/EPIC_PBMC2NormMix_LM22-Full.tsv
python B_NormFile.py ../2ReformatPredictions/ReformattedPredictions/EPIC_StromalNormMix_BluePrint-Blood.tsv > NormedPredictions/EPIC_StromalNormMix_BluePrint-Blood.tsv
python B_NormFile.py ../2ReformatPredictions/ReformattedPredictions/EPIC_StromalNormMix_EPIC-BCIC.tsv > NormedPredictions/EPIC_StromalNormMix_EPIC-BCIC.tsv
python B_NormFile.py ../2ReformatPredictions/ReformattedPredictions/EPIC_StromalNormMix_EPIC-TIC.tsv > NormedPredictions/EPIC_StromalNormMix_EPIC-TIC.tsv
python B_NormFile.py ../2ReformatPredictions/ReformattedPredictions/EPIC_StromalNormMix_HPCA-Blood.tsv > NormedPredictions/EPIC_StromalNormMix_HPCA-Blood.tsv
python B_NormFile.py ../2ReformatPredictions/ReformattedPredictions/EPIC_StromalNormMix_HPCA-Stromal.tsv > NormedPredictions/EPIC_StromalNormMix_HPCA-Stromal.tsv
python B_NormFile.py ../2ReformatPredictions/ReformattedPredictions/EPIC_StromalNormMix_ImmunoStates-Blood.tsv > NormedPredictions/EPIC_StromalNormMix_ImmunoStates-Blood.tsv
python B_NormFile.py ../2ReformatPredictions/ReformattedPredictions/EPIC_StromalNormMix_ImmunoStates-Full.tsv > NormedPredictions/EPIC_StromalNormMix_ImmunoStates-Full.tsv
python B_NormFile.py ../2ReformatPredictions/ReformattedPredictions/EPIC_StromalNormMix_ImmunoStates-Stromal.tsv > NormedPredictions/EPIC_StromalNormMix_ImmunoStates-Stromal.tsv
python B_NormFile.py ../2ReformatPredictions/ReformattedPredictions/EPIC_StromalNormMix_LM22-Blood.tsv > NormedPredictions/EPIC_StromalNormMix_LM22-Blood.tsv
python B_NormFile.py ../2ReformatPredictions/ReformattedPredictions/EPIC_StromalNormMix_LM22-Full.tsv > NormedPredictions/EPIC_StromalNormMix_LM22-Full.tsv
python B_NormFile.py ../2ReformatPredictions/ReformattedPredictions/EPIC_StromalNormMix_LM22-Stromal.tsv > NormedPredictions/EPIC_StromalNormMix_LM22-Stromal.tsv
python B_NormFile.py ../2ReformatPredictions/ReformattedPredictions/GEDIT_CellMixtures.tsv_BluePrint-Blood.tsv > NormedPredictions/GEDIT_CellMixtures.tsv_BluePrint-Blood.tsv
python B_NormFile.py ../2ReformatPredictions/ReformattedPredictions/GEDIT_CellMixtures.tsv_EPIC-BCIC.tsv > NormedPredictions/GEDIT_CellMixtures.tsv_EPIC-BCIC.tsv
python B_NormFile.py ../2ReformatPredictions/ReformattedPredictions/GEDIT_CellMixtures.tsv_EPIC-TIC.tsv > NormedPredictions/GEDIT_CellMixtures.tsv_EPIC-TIC.tsv
python B_NormFile.py ../2ReformatPredictions/ReformattedPredictions/GEDIT_CellMixtures.tsv_HPCA-Blood.tsv > NormedPredictions/GEDIT_CellMixtures.tsv_HPCA-Blood.tsv
python B_NormFile.py ../2ReformatPredictions/ReformattedPredictions/GEDIT_CellMixtures.tsv_HPCA-Stromal.tsv > NormedPredictions/GEDIT_CellMixtures.tsv_HPCA-Stromal.tsv
python B_NormFile.py ../2ReformatPredictions/ReformattedPredictions/GEDIT_CellMixtures.tsv_ImmunoStates-Blood.tsv > NormedPredictions/GEDIT_CellMixtures.tsv_ImmunoStates-Blood.tsv
python B_NormFile.py ../2ReformatPredictions/ReformattedPredictions/GEDIT_CellMixtures.tsv_ImmunoStates-Full.tsv > NormedPredictions/GEDIT_CellMixtures.tsv_ImmunoStates-Full.tsv
python B_NormFile.py ../2ReformatPredictions/ReformattedPredictions/GEDIT_CellMixtures.tsv_ImmunoStates-Stromal.tsv > NormedPredictions/GEDIT_CellMixtures.tsv_ImmunoStates-Stromal.tsv
python B_NormFile.py ../2ReformatPredictions/ReformattedPredictions/GEDIT_CellMixtures.tsv_LM22-Blood.tsv > NormedPredictions/GEDIT_CellMixtures.tsv_LM22-Blood.tsv
python B_NormFile.py ../2ReformatPredictions/ReformattedPredictions/GEDIT_CellMixtures.tsv_LM22-Full.tsv > NormedPredictions/GEDIT_CellMixtures.tsv_LM22-Full.tsv
python B_NormFile.py ../2ReformatPredictions/ReformattedPredictions/GEDIT_CellMixtures.tsv_LM22-Stromal.tsv > NormedPredictions/GEDIT_CellMixtures.tsv_LM22-Stromal.tsv
python B_NormFile.py ../2ReformatPredictions/ReformattedPredictions/GEDIT_CellMixtures_10XImmune.tsv > NormedPredictions/GEDIT_CellMixtures_10XImmune.tsv
python B_NormFile.py ../2ReformatPredictions/ReformattedPredictions/GEDIT_CellMixtures_BlueCodeV1.tsv > NormedPredictions/GEDIT_CellMixtures_BlueCodeV1.tsv
python B_NormFile.py ../2ReformatPredictions/ReformattedPredictions/GEDIT_CellMixtures_BluePrint-Blood.tsv > NormedPredictions/GEDIT_CellMixtures_BluePrint-Blood.tsv
python B_NormFile.py ../2ReformatPredictions/ReformattedPredictions/GEDIT_CellMixtures_EPIC-BCIC.tsv > NormedPredictions/GEDIT_CellMixtures_EPIC-BCIC.tsv
python B_NormFile.py ../2ReformatPredictions/ReformattedPredictions/GEDIT_CellMixtures_EPIC-TIC.tsv > NormedPredictions/GEDIT_CellMixtures_EPIC-TIC.tsv
python B_NormFile.py ../2ReformatPredictions/ReformattedPredictions/GEDIT_CellMixtures_HPCA-Blood.tsv > NormedPredictions/GEDIT_CellMixtures_HPCA-Blood.tsv
python B_NormFile.py ../2ReformatPredictions/ReformattedPredictions/GEDIT_CellMixtures_HPCA-Stromal.tsv > NormedPredictions/GEDIT_CellMixtures_HPCA-Stromal.tsv
python B_NormFile.py ../2ReformatPredictions/ReformattedPredictions/GEDIT_CellMixtures_ImmunoStates-Blood.tsv > NormedPredictions/GEDIT_CellMixtures_ImmunoStates-Blood.tsv
python B_NormFile.py ../2ReformatPredictions/ReformattedPredictions/GEDIT_CellMixtures_ImmunoStates-Full.tsv > NormedPredictions/GEDIT_CellMixtures_ImmunoStates-Full.tsv
python B_NormFile.py ../2ReformatPredictions/ReformattedPredictions/GEDIT_CellMixtures_ImmunoStates-Stromal.tsv > NormedPredictions/GEDIT_CellMixtures_ImmunoStates-Stromal.tsv
python B_NormFile.py ../2ReformatPredictions/ReformattedPredictions/GEDIT_CellMixtures_LM22-Blood.tsv > NormedPredictions/GEDIT_CellMixtures_LM22-Blood.tsv
python B_NormFile.py ../2ReformatPredictions/ReformattedPredictions/GEDIT_CellMixtures_LM22-Full.tsv > NormedPredictions/GEDIT_CellMixtures_LM22-Full.tsv
python B_NormFile.py ../2ReformatPredictions/ReformattedPredictions/GEDIT_CellMixtures_LM22-Stromal.tsv > NormedPredictions/GEDIT_CellMixtures_LM22-Stromal.tsv
python B_NormFile.py ../2ReformatPredictions/ReformattedPredictions/GEDIT_CellMixtures_SkinSignaturesV1.tsv > NormedPredictions/GEDIT_CellMixtures_SkinSignaturesV1.tsv
python B_NormFile.py ../2ReformatPredictions/ReformattedPredictions/GEDIT_Fram.tsv_BluePrint-Blood.tsv > NormedPredictions/GEDIT_Fram.tsv_BluePrint-Blood.tsv
python B_NormFile.py ../2ReformatPredictions/ReformattedPredictions/GEDIT_Fram.tsv_EPIC-BCIC.tsv > NormedPredictions/GEDIT_Fram.tsv_EPIC-BCIC.tsv
python B_NormFile.py ../2ReformatPredictions/ReformattedPredictions/GEDIT_Fram.tsv_EPIC-TIC.tsv > NormedPredictions/GEDIT_Fram.tsv_EPIC-TIC.tsv
python B_NormFile.py ../2ReformatPredictions/ReformattedPredictions/GEDIT_Fram.tsv_HPCA-Blood.tsv > NormedPredictions/GEDIT_Fram.tsv_HPCA-Blood.tsv
python B_NormFile.py ../2ReformatPredictions/ReformattedPredictions/GEDIT_Fram.tsv_HPCA-Stromal.tsv > NormedPredictions/GEDIT_Fram.tsv_HPCA-Stromal.tsv
python B_NormFile.py ../2ReformatPredictions/ReformattedPredictions/GEDIT_Fram.tsv_ImmunoStates-Blood.tsv > NormedPredictions/GEDIT_Fram.tsv_ImmunoStates-Blood.tsv
python B_NormFile.py ../2ReformatPredictions/ReformattedPredictions/GEDIT_Fram.tsv_ImmunoStates-Full.tsv > NormedPredictions/GEDIT_Fram.tsv_ImmunoStates-Full.tsv
python B_NormFile.py ../2ReformatPredictions/ReformattedPredictions/GEDIT_Fram.tsv_ImmunoStates-Stromal.tsv > NormedPredictions/GEDIT_Fram.tsv_ImmunoStates-Stromal.tsv
python B_NormFile.py ../2ReformatPredictions/ReformattedPredictions/GEDIT_Fram.tsv_LM22-Blood.tsv > NormedPredictions/GEDIT_Fram.tsv_LM22-Blood.tsv
python B_NormFile.py ../2ReformatPredictions/ReformattedPredictions/GEDIT_Fram.tsv_LM22-Full.tsv > NormedPredictions/GEDIT_Fram.tsv_LM22-Full.tsv
python B_NormFile.py ../2ReformatPredictions/ReformattedPredictions/GEDIT_Fram.tsv_LM22-Stromal.tsv > NormedPredictions/GEDIT_Fram.tsv_LM22-Stromal.tsv
python B_NormFile.py ../2ReformatPredictions/ReformattedPredictions/GEDIT_Fram_10XImmune.tsv > NormedPredictions/GEDIT_Fram_10XImmune.tsv
python B_NormFile.py ../2ReformatPredictions/ReformattedPredictions/GEDIT_Fram_BlueCodeV1.tsv > NormedPredictions/GEDIT_Fram_BlueCodeV1.tsv
python B_NormFile.py ../2ReformatPredictions/ReformattedPredictions/GEDIT_Fram_BluePrint-Blood.tsv > NormedPredictions/GEDIT_Fram_BluePrint-Blood.tsv
python B_NormFile.py ../2ReformatPredictions/ReformattedPredictions/GEDIT_Fram_EPIC-BCIC.tsv > NormedPredictions/GEDIT_Fram_EPIC-BCIC.tsv
python B_NormFile.py ../2ReformatPredictions/ReformattedPredictions/GEDIT_Fram_EPIC-TIC.tsv > NormedPredictions/GEDIT_Fram_EPIC-TIC.tsv
python B_NormFile.py ../2ReformatPredictions/ReformattedPredictions/GEDIT_Fram_HPCA-Blood.tsv > NormedPredictions/GEDIT_Fram_HPCA-Blood.tsv
python B_NormFile.py ../2ReformatPredictions/ReformattedPredictions/GEDIT_Fram_HPCA-Stromal.tsv > NormedPredictions/GEDIT_Fram_HPCA-Stromal.tsv
python B_NormFile.py ../2ReformatPredictions/ReformattedPredictions/GEDIT_Fram_ImmunoStates-Blood.tsv > NormedPredictions/GEDIT_Fram_ImmunoStates-Blood.tsv
python B_NormFile.py ../2ReformatPredictions/ReformattedPredictions/GEDIT_Fram_ImmunoStates-Full.tsv > NormedPredictions/GEDIT_Fram_ImmunoStates-Full.tsv
python B_NormFile.py ../2ReformatPredictions/ReformattedPredictions/GEDIT_Fram_ImmunoStates-Stromal.tsv > NormedPredictions/GEDIT_Fram_ImmunoStates-Stromal.tsv
python B_NormFile.py ../2ReformatPredictions/ReformattedPredictions/GEDIT_Fram_LM22-Blood.tsv > NormedPredictions/GEDIT_Fram_LM22-Blood.tsv
python B_NormFile.py ../2ReformatPredictions/ReformattedPredictions/GEDIT_Fram_LM22-Full.tsv > NormedPredictions/GEDIT_Fram_LM22-Full.tsv
python B_NormFile.py ../2ReformatPredictions/ReformattedPredictions/GEDIT_Fram_LM22-Stromal.tsv > NormedPredictions/GEDIT_Fram_LM22-Stromal.tsv
python B_NormFile.py ../2ReformatPredictions/ReformattedPredictions/GEDIT_Fram_SkinSignaturesV1.tsv > NormedPredictions/GEDIT_Fram_SkinSignaturesV1.tsv
python B_NormFile.py ../2ReformatPredictions/ReformattedPredictions/GEDIT_PBMC1NormMix.tsv_BluePrint-Blood.tsv > NormedPredictions/GEDIT_PBMC1NormMix.tsv_BluePrint-Blood.tsv
python B_NormFile.py ../2ReformatPredictions/ReformattedPredictions/GEDIT_PBMC1NormMix.tsv_EPIC-BCIC.tsv > NormedPredictions/GEDIT_PBMC1NormMix.tsv_EPIC-BCIC.tsv
python B_NormFile.py ../2ReformatPredictions/ReformattedPredictions/GEDIT_PBMC1NormMix.tsv_EPIC-TIC.tsv > NormedPredictions/GEDIT_PBMC1NormMix.tsv_EPIC-TIC.tsv
python B_NormFile.py ../2ReformatPredictions/ReformattedPredictions/GEDIT_PBMC1NormMix.tsv_HPCA-Blood.tsv > NormedPredictions/GEDIT_PBMC1NormMix.tsv_HPCA-Blood.tsv
python B_NormFile.py ../2ReformatPredictions/ReformattedPredictions/GEDIT_PBMC1NormMix.tsv_HPCA-Stromal.tsv > NormedPredictions/GEDIT_PBMC1NormMix.tsv_HPCA-Stromal.tsv
python B_NormFile.py ../2ReformatPredictions/ReformattedPredictions/GEDIT_PBMC1NormMix.tsv_ImmunoStates-Blood.tsv > NormedPredictions/GEDIT_PBMC1NormMix.tsv_ImmunoStates-Blood.tsv
python B_NormFile.py ../2ReformatPredictions/ReformattedPredictions/GEDIT_PBMC1NormMix.tsv_ImmunoStates-Full.tsv > NormedPredictions/GEDIT_PBMC1NormMix.tsv_ImmunoStates-Full.tsv
python B_NormFile.py ../2ReformatPredictions/ReformattedPredictions/GEDIT_PBMC1NormMix.tsv_ImmunoStates-Stromal.tsv > NormedPredictions/GEDIT_PBMC1NormMix.tsv_ImmunoStates-Stromal.tsv
python B_NormFile.py ../2ReformatPredictions/ReformattedPredictions/GEDIT_PBMC1NormMix.tsv_LM22-Blood.tsv > NormedPredictions/GEDIT_PBMC1NormMix.tsv_LM22-Blood.tsv
python B_NormFile.py ../2ReformatPredictions/ReformattedPredictions/GEDIT_PBMC1NormMix.tsv_LM22-Full.tsv > NormedPredictions/GEDIT_PBMC1NormMix.tsv_LM22-Full.tsv
python B_NormFile.py ../2ReformatPredictions/ReformattedPredictions/GEDIT_PBMC1NormMix.tsv_LM22-Stromal.tsv > NormedPredictions/GEDIT_PBMC1NormMix.tsv_LM22-Stromal.tsv
python B_NormFile.py ../2ReformatPredictions/ReformattedPredictions/GEDIT_PBMC1NormMix_10XImmune.tsv > NormedPredictions/GEDIT_PBMC1NormMix_10XImmune.tsv
python B_NormFile.py ../2ReformatPredictions/ReformattedPredictions/GEDIT_PBMC1NormMix_BlueCodeV1.tsv > NormedPredictions/GEDIT_PBMC1NormMix_BlueCodeV1.tsv
python B_NormFile.py ../2ReformatPredictions/ReformattedPredictions/GEDIT_PBMC1NormMix_BluePrint-Blood.tsv > NormedPredictions/GEDIT_PBMC1NormMix_BluePrint-Blood.tsv
python B_NormFile.py ../2ReformatPredictions/ReformattedPredictions/GEDIT_PBMC1NormMix_EPIC-BCIC.tsv > NormedPredictions/GEDIT_PBMC1NormMix_EPIC-BCIC.tsv
python B_NormFile.py ../2ReformatPredictions/ReformattedPredictions/GEDIT_PBMC1NormMix_EPIC-TIC.tsv > NormedPredictions/GEDIT_PBMC1NormMix_EPIC-TIC.tsv
python B_NormFile.py ../2ReformatPredictions/ReformattedPredictions/GEDIT_PBMC1NormMix_HPCA-Blood.tsv > NormedPredictions/GEDIT_PBMC1NormMix_HPCA-Blood.tsv
python B_NormFile.py ../2ReformatPredictions/ReformattedPredictions/GEDIT_PBMC1NormMix_HPCA-Stromal.tsv > NormedPredictions/GEDIT_PBMC1NormMix_HPCA-Stromal.tsv
python B_NormFile.py ../2ReformatPredictions/ReformattedPredictions/GEDIT_PBMC1NormMix_ImmunoStates-Blood.tsv > NormedPredictions/GEDIT_PBMC1NormMix_ImmunoStates-Blood.tsv
python B_NormFile.py ../2ReformatPredictions/ReformattedPredictions/GEDIT_PBMC1NormMix_ImmunoStates-Full.tsv > NormedPredictions/GEDIT_PBMC1NormMix_ImmunoStates-Full.tsv
python B_NormFile.py ../2ReformatPredictions/ReformattedPredictions/GEDIT_PBMC1NormMix_ImmunoStates-Stromal.tsv > NormedPredictions/GEDIT_PBMC1NormMix_ImmunoStates-Stromal.tsv
python B_NormFile.py ../2ReformatPredictions/ReformattedPredictions/GEDIT_PBMC1NormMix_LM22-Blood.tsv > NormedPredictions/GEDIT_PBMC1NormMix_LM22-Blood.tsv
python B_NormFile.py ../2ReformatPredictions/ReformattedPredictions/GEDIT_PBMC1NormMix_LM22-Full.tsv > NormedPredictions/GEDIT_PBMC1NormMix_LM22-Full.tsv
python B_NormFile.py ../2ReformatPredictions/ReformattedPredictions/GEDIT_PBMC1NormMix_LM22-Stromal.tsv > NormedPredictions/GEDIT_PBMC1NormMix_LM22-Stromal.tsv
python B_NormFile.py ../2ReformatPredictions/ReformattedPredictions/GEDIT_PBMC1NormMix_SkinSignaturesV1.tsv > NormedPredictions/GEDIT_PBMC1NormMix_SkinSignaturesV1.tsv
python B_NormFile.py ../2ReformatPredictions/ReformattedPredictions/GEDIT_PBMC2NormMix.tsv_BluePrint-Blood.tsv > NormedPredictions/GEDIT_PBMC2NormMix.tsv_BluePrint-Blood.tsv
python B_NormFile.py ../2ReformatPredictions/ReformattedPredictions/GEDIT_PBMC2NormMix.tsv_EPIC-BCIC.tsv > NormedPredictions/GEDIT_PBMC2NormMix.tsv_EPIC-BCIC.tsv
python B_NormFile.py ../2ReformatPredictions/ReformattedPredictions/GEDIT_PBMC2NormMix.tsv_EPIC-TIC.tsv > NormedPredictions/GEDIT_PBMC2NormMix.tsv_EPIC-TIC.tsv
python B_NormFile.py ../2ReformatPredictions/ReformattedPredictions/GEDIT_PBMC2NormMix.tsv_HPCA-Blood.tsv > NormedPredictions/GEDIT_PBMC2NormMix.tsv_HPCA-Blood.tsv
python B_NormFile.py ../2ReformatPredictions/ReformattedPredictions/GEDIT_PBMC2NormMix.tsv_HPCA-Stromal.tsv > NormedPredictions/GEDIT_PBMC2NormMix.tsv_HPCA-Stromal.tsv
python B_NormFile.py ../2ReformatPredictions/ReformattedPredictions/GEDIT_PBMC2NormMix.tsv_ImmunoStates-Blood.tsv > NormedPredictions/GEDIT_PBMC2NormMix.tsv_ImmunoStates-Blood.tsv
python B_NormFile.py ../2ReformatPredictions/ReformattedPredictions/GEDIT_PBMC2NormMix.tsv_ImmunoStates-Full.tsv > NormedPredictions/GEDIT_PBMC2NormMix.tsv_ImmunoStates-Full.tsv
python B_NormFile.py ../2ReformatPredictions/ReformattedPredictions/GEDIT_PBMC2NormMix.tsv_ImmunoStates-Stromal.tsv > NormedPredictions/GEDIT_PBMC2NormMix.tsv_ImmunoStates-Stromal.tsv
python B_NormFile.py ../2ReformatPredictions/ReformattedPredictions/GEDIT_PBMC2NormMix.tsv_LM22-Blood.tsv > NormedPredictions/GEDIT_PBMC2NormMix.tsv_LM22-Blood.tsv
python B_NormFile.py ../2ReformatPredictions/ReformattedPredictions/GEDIT_PBMC2NormMix.tsv_LM22-Full.tsv > NormedPredictions/GEDIT_PBMC2NormMix.tsv_LM22-Full.tsv
python B_NormFile.py ../2ReformatPredictions/ReformattedPredictions/GEDIT_PBMC2NormMix.tsv_LM22-Stromal.tsv > NormedPredictions/GEDIT_PBMC2NormMix.tsv_LM22-Stromal.tsv
python B_NormFile.py ../2ReformatPredictions/ReformattedPredictions/GEDIT_PBMC2NormMix_10XImmune.tsv > NormedPredictions/GEDIT_PBMC2NormMix_10XImmune.tsv
python B_NormFile.py ../2ReformatPredictions/ReformattedPredictions/GEDIT_PBMC2NormMix_BlueCodeV1.tsv > NormedPredictions/GEDIT_PBMC2NormMix_BlueCodeV1.tsv
python B_NormFile.py ../2ReformatPredictions/ReformattedPredictions/GEDIT_PBMC2NormMix_BluePrint-Blood.tsv > NormedPredictions/GEDIT_PBMC2NormMix_BluePrint-Blood.tsv
python B_NormFile.py ../2ReformatPredictions/ReformattedPredictions/GEDIT_PBMC2NormMix_EPIC-BCIC.tsv > NormedPredictions/GEDIT_PBMC2NormMix_EPIC-BCIC.tsv
python B_NormFile.py ../2ReformatPredictions/ReformattedPredictions/GEDIT_PBMC2NormMix_EPIC-TIC.tsv > NormedPredictions/GEDIT_PBMC2NormMix_EPIC-TIC.tsv
python B_NormFile.py ../2ReformatPredictions/ReformattedPredictions/GEDIT_PBMC2NormMix_HPCA-Blood.tsv > NormedPredictions/GEDIT_PBMC2NormMix_HPCA-Blood.tsv
python B_NormFile.py ../2ReformatPredictions/ReformattedPredictions/GEDIT_PBMC2NormMix_HPCA-Stromal.tsv > NormedPredictions/GEDIT_PBMC2NormMix_HPCA-Stromal.tsv
python B_NormFile.py ../2ReformatPredictions/ReformattedPredictions/GEDIT_PBMC2NormMix_ImmunoStates-Blood.tsv > NormedPredictions/GEDIT_PBMC2NormMix_ImmunoStates-Blood.tsv
python B_NormFile.py ../2ReformatPredictions/ReformattedPredictions/GEDIT_PBMC2NormMix_ImmunoStates-Full.tsv > NormedPredictions/GEDIT_PBMC2NormMix_ImmunoStates-Full.tsv
python B_NormFile.py ../2ReformatPredictions/ReformattedPredictions/GEDIT_PBMC2NormMix_ImmunoStates-Stromal.tsv > NormedPredictions/GEDIT_PBMC2NormMix_ImmunoStates-Stromal.tsv
python B_NormFile.py ../2ReformatPredictions/ReformattedPredictions/GEDIT_PBMC2NormMix_LM22-Blood.tsv > NormedPredictions/GEDIT_PBMC2NormMix_LM22-Blood.tsv
python B_NormFile.py ../2ReformatPredictions/ReformattedPredictions/GEDIT_PBMC2NormMix_LM22-Full.tsv > NormedPredictions/GEDIT_PBMC2NormMix_LM22-Full.tsv
python B_NormFile.py ../2ReformatPredictions/ReformattedPredictions/GEDIT_PBMC2NormMix_LM22-Stromal.tsv > NormedPredictions/GEDIT_PBMC2NormMix_LM22-Stromal.tsv
python B_NormFile.py ../2ReformatPredictions/ReformattedPredictions/GEDIT_PBMC2NormMix_SkinSignaturesV1.tsv > NormedPredictions/GEDIT_PBMC2NormMix_SkinSignaturesV1.tsv
python B_NormFile.py ../2ReformatPredictions/ReformattedPredictions/GEDIT_StromalNormMix.tsv_BluePrint-Blood.tsv > NormedPredictions/GEDIT_StromalNormMix.tsv_BluePrint-Blood.tsv
python B_NormFile.py ../2ReformatPredictions/ReformattedPredictions/GEDIT_StromalNormMix.tsv_EPIC-BCIC.tsv > NormedPredictions/GEDIT_StromalNormMix.tsv_EPIC-BCIC.tsv
python B_NormFile.py ../2ReformatPredictions/ReformattedPredictions/GEDIT_StromalNormMix.tsv_EPIC-TIC.tsv > NormedPredictions/GEDIT_StromalNormMix.tsv_EPIC-TIC.tsv
python B_NormFile.py ../2ReformatPredictions/ReformattedPredictions/GEDIT_StromalNormMix.tsv_HPCA-Blood.tsv > NormedPredictions/GEDIT_StromalNormMix.tsv_HPCA-Blood.tsv
python B_NormFile.py ../2ReformatPredictions/ReformattedPredictions/GEDIT_StromalNormMix.tsv_HPCA-Stromal.tsv > NormedPredictions/GEDIT_StromalNormMix.tsv_HPCA-Stromal.tsv
python B_NormFile.py ../2ReformatPredictions/ReformattedPredictions/GEDIT_StromalNormMix.tsv_ImmunoStates-Blood.tsv > NormedPredictions/GEDIT_StromalNormMix.tsv_ImmunoStates-Blood.tsv
python B_NormFile.py ../2ReformatPredictions/ReformattedPredictions/GEDIT_StromalNormMix.tsv_ImmunoStates-Full.tsv > NormedPredictions/GEDIT_StromalNormMix.tsv_ImmunoStates-Full.tsv
python B_NormFile.py ../2ReformatPredictions/ReformattedPredictions/GEDIT_StromalNormMix.tsv_ImmunoStates-Stromal.tsv > NormedPredictions/GEDIT_StromalNormMix.tsv_ImmunoStates-Stromal.tsv
python B_NormFile.py ../2ReformatPredictions/ReformattedPredictions/GEDIT_StromalNormMix.tsv_LM22-Blood.tsv > NormedPredictions/GEDIT_StromalNormMix.tsv_LM22-Blood.tsv
python B_NormFile.py ../2ReformatPredictions/ReformattedPredictions/GEDIT_StromalNormMix.tsv_LM22-Full.tsv > NormedPredictions/GEDIT_StromalNormMix.tsv_LM22-Full.tsv
python B_NormFile.py ../2ReformatPredictions/ReformattedPredictions/GEDIT_StromalNormMix.tsv_LM22-Stromal.tsv > NormedPredictions/GEDIT_StromalNormMix.tsv_LM22-Stromal.tsv
python B_NormFile.py ../2ReformatPredictions/ReformattedPredictions/GEDIT_StromalNormMix_10XImmune.tsv > NormedPredictions/GEDIT_StromalNormMix_10XImmune.tsv
python B_NormFile.py ../2ReformatPredictions/ReformattedPredictions/GEDIT_StromalNormMix_BlueCodeV1.tsv > NormedPredictions/GEDIT_StromalNormMix_BlueCodeV1.tsv
python B_NormFile.py ../2ReformatPredictions/ReformattedPredictions/GEDIT_StromalNormMix_BluePrint-Blood.tsv > NormedPredictions/GEDIT_StromalNormMix_BluePrint-Blood.tsv
python B_NormFile.py ../2ReformatPredictions/ReformattedPredictions/GEDIT_StromalNormMix_EPIC-BCIC.tsv > NormedPredictions/GEDIT_StromalNormMix_EPIC-BCIC.tsv
python B_NormFile.py ../2ReformatPredictions/ReformattedPredictions/GEDIT_StromalNormMix_EPIC-TIC.tsv > NormedPredictions/GEDIT_StromalNormMix_EPIC-TIC.tsv
python B_NormFile.py ../2ReformatPredictions/ReformattedPredictions/GEDIT_StromalNormMix_HPCA-Blood.tsv > NormedPredictions/GEDIT_StromalNormMix_HPCA-Blood.tsv
python B_NormFile.py ../2ReformatPredictions/ReformattedPredictions/GEDIT_StromalNormMix_HPCA-Stromal.tsv > NormedPredictions/GEDIT_StromalNormMix_HPCA-Stromal.tsv
python B_NormFile.py ../2ReformatPredictions/ReformattedPredictions/GEDIT_StromalNormMix_ImmunoStates-Blood.tsv > NormedPredictions/GEDIT_StromalNormMix_ImmunoStates-Blood.tsv
python B_NormFile.py ../2ReformatPredictions/ReformattedPredictions/GEDIT_StromalNormMix_ImmunoStates-Full.tsv > NormedPredictions/GEDIT_StromalNormMix_ImmunoStates-Full.tsv
python B_NormFile.py ../2ReformatPredictions/ReformattedPredictions/GEDIT_StromalNormMix_ImmunoStates-Stromal.tsv > NormedPredictions/GEDIT_StromalNormMix_ImmunoStates-Stromal.tsv
python B_NormFile.py ../2ReformatPredictions/ReformattedPredictions/GEDIT_StromalNormMix_LM22-Blood.tsv > NormedPredictions/GEDIT_StromalNormMix_LM22-Blood.tsv
python B_NormFile.py ../2ReformatPredictions/ReformattedPredictions/GEDIT_StromalNormMix_LM22-Full.tsv > NormedPredictions/GEDIT_StromalNormMix_LM22-Full.tsv
python B_NormFile.py ../2ReformatPredictions/ReformattedPredictions/GEDIT_StromalNormMix_LM22-Stromal.tsv > NormedPredictions/GEDIT_StromalNormMix_LM22-Stromal.tsv
python B_NormFile.py ../2ReformatPredictions/ReformattedPredictions/GEDIT_StromalNormMix_SkinSignaturesV1.tsv > NormedPredictions/GEDIT_StromalNormMix_SkinSignaturesV1.tsv
python B_NormFile.py ../2ReformatPredictions/ReformattedPredictions/MCP_CellMixtures_default.tsv > NormedPredictions/MCP_CellMixtures_default.tsv
python B_NormFile.py ../2ReformatPredictions/ReformattedPredictions/MCP_Fram_default.tsv > NormedPredictions/MCP_Fram_default.tsv
python B_NormFile.py ../2ReformatPredictions/ReformattedPredictions/MCP_PBMC1NormMix_default.tsv > NormedPredictions/MCP_PBMC1NormMix_default.tsv
python B_NormFile.py ../2ReformatPredictions/ReformattedPredictions/MCP_PBMC2NormMix_default.tsv > NormedPredictions/MCP_PBMC2NormMix_default.tsv
python B_NormFile.py ../2ReformatPredictions/ReformattedPredictions/MCP_StromalNormMix_default.tsv > NormedPredictions/MCP_StromalNormMix_default.tsv
python B_NormFile.py ../2ReformatPredictions/ReformattedPredictions/Savant_CellMixtures_10xSigs.tsv > NormedPredictions/Savant_CellMixtures_10xSigs.tsv
python B_NormFile.py ../2ReformatPredictions/ReformattedPredictions/Savant_CellMixtures_BlueCode.tsv > NormedPredictions/Savant_CellMixtures_BlueCode.tsv
python B_NormFile.py ../2ReformatPredictions/ReformattedPredictions/Savant_CellMixtures_BluePrint-Blood.tsv > NormedPredictions/Savant_CellMixtures_BluePrint-Blood.tsv
python B_NormFile.py ../2ReformatPredictions/ReformattedPredictions/Savant_CellMixtures_EPIC-BCIC.tsv > NormedPredictions/Savant_CellMixtures_EPIC-BCIC.tsv
python B_NormFile.py ../2ReformatPredictions/ReformattedPredictions/Savant_CellMixtures_EPIC-TIC.tsv > NormedPredictions/Savant_CellMixtures_EPIC-TIC.tsv
python B_NormFile.py ../2ReformatPredictions/ReformattedPredictions/Savant_CellMixtures_HPCA-Blood.tsv > NormedPredictions/Savant_CellMixtures_HPCA-Blood.tsv
python B_NormFile.py ../2ReformatPredictions/ReformattedPredictions/Savant_CellMixtures_HPCA-Stromal.tsv > NormedPredictions/Savant_CellMixtures_HPCA-Stromal.tsv
python B_NormFile.py ../2ReformatPredictions/ReformattedPredictions/Savant_CellMixtures_ImmuneCellSignatures.tsv > NormedPredictions/Savant_CellMixtures_ImmuneCellSignatures.tsv
python B_NormFile.py ../2ReformatPredictions/ReformattedPredictions/Savant_CellMixtures_ImmunoStates-Blood.tsv > NormedPredictions/Savant_CellMixtures_ImmunoStates-Blood.tsv
python B_NormFile.py ../2ReformatPredictions/ReformattedPredictions/Savant_CellMixtures_ImmunoStates-Full.tsv > NormedPredictions/Savant_CellMixtures_ImmunoStates-Full.tsv
python B_NormFile.py ../2ReformatPredictions/ReformattedPredictions/Savant_CellMixtures_ImmunoStates-Stromal.tsv > NormedPredictions/Savant_CellMixtures_ImmunoStates-Stromal.tsv
python B_NormFile.py ../2ReformatPredictions/ReformattedPredictions/Savant_CellMixtures_LM22-Blood.tsv > NormedPredictions/Savant_CellMixtures_LM22-Blood.tsv
python B_NormFile.py ../2ReformatPredictions/ReformattedPredictions/Savant_CellMixtures_LM22-Full.tsv > NormedPredictions/Savant_CellMixtures_LM22-Full.tsv
python B_NormFile.py ../2ReformatPredictions/ReformattedPredictions/Savant_CellMixtures_LM22-Stromal.tsv > NormedPredictions/Savant_CellMixtures_LM22-Stromal.tsv
python B_NormFile.py ../2ReformatPredictions/ReformattedPredictions/Savant_CellMixtures_SkinSigs.tsv > NormedPredictions/Savant_CellMixtures_SkinSigs.tsv
python B_NormFile.py ../2ReformatPredictions/ReformattedPredictions/Savant_Fram_10xSigs.tsv > NormedPredictions/Savant_Fram_10xSigs.tsv
python B_NormFile.py ../2ReformatPredictions/ReformattedPredictions/Savant_Fram_BlueCode.tsv > NormedPredictions/Savant_Fram_BlueCode.tsv
python B_NormFile.py ../2ReformatPredictions/ReformattedPredictions/Savant_Fram_BluePrint-Blood.tsv > NormedPredictions/Savant_Fram_BluePrint-Blood.tsv
python B_NormFile.py ../2ReformatPredictions/ReformattedPredictions/Savant_Fram_EPIC-BCIC.tsv > NormedPredictions/Savant_Fram_EPIC-BCIC.tsv
python B_NormFile.py ../2ReformatPredictions/ReformattedPredictions/Savant_Fram_EPIC-TIC.tsv > NormedPredictions/Savant_Fram_EPIC-TIC.tsv
python B_NormFile.py ../2ReformatPredictions/ReformattedPredictions/Savant_Fram_HPCA-Blood.tsv > NormedPredictions/Savant_Fram_HPCA-Blood.tsv
python B_NormFile.py ../2ReformatPredictions/ReformattedPredictions/Savant_Fram_HPCA-Stromal.tsv > NormedPredictions/Savant_Fram_HPCA-Stromal.tsv
python B_NormFile.py ../2ReformatPredictions/ReformattedPredictions/Savant_Fram_ImmuneCellSignatures.tsv > NormedPredictions/Savant_Fram_ImmuneCellSignatures.tsv
python B_NormFile.py ../2ReformatPredictions/ReformattedPredictions/Savant_Fram_ImmunoStates-Blood.tsv > NormedPredictions/Savant_Fram_ImmunoStates-Blood.tsv
python B_NormFile.py ../2ReformatPredictions/ReformattedPredictions/Savant_Fram_ImmunoStates-Full.tsv > NormedPredictions/Savant_Fram_ImmunoStates-Full.tsv
python B_NormFile.py ../2ReformatPredictions/ReformattedPredictions/Savant_Fram_ImmunoStates-Stromal.tsv > NormedPredictions/Savant_Fram_ImmunoStates-Stromal.tsv
python B_NormFile.py ../2ReformatPredictions/ReformattedPredictions/Savant_Fram_LM22-Blood.tsv > NormedPredictions/Savant_Fram_LM22-Blood.tsv
python B_NormFile.py ../2ReformatPredictions/ReformattedPredictions/Savant_Fram_LM22-Full.tsv > NormedPredictions/Savant_Fram_LM22-Full.tsv
python B_NormFile.py ../2ReformatPredictions/ReformattedPredictions/Savant_Fram_LM22-Stromal.tsv > NormedPredictions/Savant_Fram_LM22-Stromal.tsv
python B_NormFile.py ../2ReformatPredictions/ReformattedPredictions/Savant_Fram_SkinSigs.tsv > NormedPredictions/Savant_Fram_SkinSigs.tsv
python B_NormFile.py ../2ReformatPredictions/ReformattedPredictions/Savant_PBMC1NormMix_10xSigs.tsv > NormedPredictions/Savant_PBMC1NormMix_10xSigs.tsv
python B_NormFile.py ../2ReformatPredictions/ReformattedPredictions/Savant_PBMC1NormMix_BlueCode.tsv > NormedPredictions/Savant_PBMC1NormMix_BlueCode.tsv
python B_NormFile.py ../2ReformatPredictions/ReformattedPredictions/Savant_PBMC1NormMix_BluePrint-Blood.tsv > NormedPredictions/Savant_PBMC1NormMix_BluePrint-Blood.tsv
python B_NormFile.py ../2ReformatPredictions/ReformattedPredictions/Savant_PBMC1NormMix_EPIC-BCIC.tsv > NormedPredictions/Savant_PBMC1NormMix_EPIC-BCIC.tsv
python B_NormFile.py ../2ReformatPredictions/ReformattedPredictions/Savant_PBMC1NormMix_EPIC-TIC.tsv > NormedPredictions/Savant_PBMC1NormMix_EPIC-TIC.tsv
python B_NormFile.py ../2ReformatPredictions/ReformattedPredictions/Savant_PBMC1NormMix_HPCA-Blood.tsv > NormedPredictions/Savant_PBMC1NormMix_HPCA-Blood.tsv
python B_NormFile.py ../2ReformatPredictions/ReformattedPredictions/Savant_PBMC1NormMix_HPCA-Stromal.tsv > NormedPredictions/Savant_PBMC1NormMix_HPCA-Stromal.tsv
python B_NormFile.py ../2ReformatPredictions/ReformattedPredictions/Savant_PBMC1NormMix_ImmuneCellSignatures.tsv > NormedPredictions/Savant_PBMC1NormMix_ImmuneCellSignatures.tsv
python B_NormFile.py ../2ReformatPredictions/ReformattedPredictions/Savant_PBMC1NormMix_ImmunoStates-Blood.tsv > NormedPredictions/Savant_PBMC1NormMix_ImmunoStates-Blood.tsv
python B_NormFile.py ../2ReformatPredictions/ReformattedPredictions/Savant_PBMC1NormMix_ImmunoStates-Full.tsv > NormedPredictions/Savant_PBMC1NormMix_ImmunoStates-Full.tsv
python B_NormFile.py ../2ReformatPredictions/ReformattedPredictions/Savant_PBMC1NormMix_ImmunoStates-Stromal.tsv > NormedPredictions/Savant_PBMC1NormMix_ImmunoStates-Stromal.tsv
python B_NormFile.py ../2ReformatPredictions/ReformattedPredictions/Savant_PBMC1NormMix_LM22-Blood.tsv > NormedPredictions/Savant_PBMC1NormMix_LM22-Blood.tsv
python B_NormFile.py ../2ReformatPredictions/ReformattedPredictions/Savant_PBMC1NormMix_LM22-Full.tsv > NormedPredictions/Savant_PBMC1NormMix_LM22-Full.tsv
python B_NormFile.py ../2ReformatPredictions/ReformattedPredictions/Savant_PBMC1NormMix_LM22-Stromal.tsv > NormedPredictions/Savant_PBMC1NormMix_LM22-Stromal.tsv
python B_NormFile.py ../2ReformatPredictions/ReformattedPredictions/Savant_PBMC1NormMix_SkinSigs.tsv > NormedPredictions/Savant_PBMC1NormMix_SkinSigs.tsv
python B_NormFile.py ../2ReformatPredictions/ReformattedPredictions/Savant_PBMC2NormMix_10xSigs.tsv > NormedPredictions/Savant_PBMC2NormMix_10xSigs.tsv
python B_NormFile.py ../2ReformatPredictions/ReformattedPredictions/Savant_PBMC2NormMix_BlueCode.tsv > NormedPredictions/Savant_PBMC2NormMix_BlueCode.tsv
python B_NormFile.py ../2ReformatPredictions/ReformattedPredictions/Savant_PBMC2NormMix_BluePrint-Blood.tsv > NormedPredictions/Savant_PBMC2NormMix_BluePrint-Blood.tsv
python B_NormFile.py ../2ReformatPredictions/ReformattedPredictions/Savant_PBMC2NormMix_EPIC-BCIC.tsv > NormedPredictions/Savant_PBMC2NormMix_EPIC-BCIC.tsv
python B_NormFile.py ../2ReformatPredictions/ReformattedPredictions/Savant_PBMC2NormMix_EPIC-TIC.tsv > NormedPredictions/Savant_PBMC2NormMix_EPIC-TIC.tsv
python B_NormFile.py ../2ReformatPredictions/ReformattedPredictions/Savant_PBMC2NormMix_HPCA-Blood.tsv > NormedPredictions/Savant_PBMC2NormMix_HPCA-Blood.tsv
python B_NormFile.py ../2ReformatPredictions/ReformattedPredictions/Savant_PBMC2NormMix_HPCA-Stromal.tsv > NormedPredictions/Savant_PBMC2NormMix_HPCA-Stromal.tsv
python B_NormFile.py ../2ReformatPredictions/ReformattedPredictions/Savant_PBMC2NormMix_ImmuneCellSignatures.tsv > NormedPredictions/Savant_PBMC2NormMix_ImmuneCellSignatures.tsv
python B_NormFile.py ../2ReformatPredictions/ReformattedPredictions/Savant_PBMC2NormMix_ImmunoStates-Blood.tsv > NormedPredictions/Savant_PBMC2NormMix_ImmunoStates-Blood.tsv
python B_NormFile.py ../2ReformatPredictions/ReformattedPredictions/Savant_PBMC2NormMix_ImmunoStates-Full.tsv > NormedPredictions/Savant_PBMC2NormMix_ImmunoStates-Full.tsv
python B_NormFile.py ../2ReformatPredictions/ReformattedPredictions/Savant_PBMC2NormMix_ImmunoStates-Stromal.tsv > NormedPredictions/Savant_PBMC2NormMix_ImmunoStates-Stromal.tsv
python B_NormFile.py ../2ReformatPredictions/ReformattedPredictions/Savant_PBMC2NormMix_LM22-Blood.tsv > NormedPredictions/Savant_PBMC2NormMix_LM22-Blood.tsv
python B_NormFile.py ../2ReformatPredictions/ReformattedPredictions/Savant_PBMC2NormMix_LM22-Full.tsv > NormedPredictions/Savant_PBMC2NormMix_LM22-Full.tsv
python B_NormFile.py ../2ReformatPredictions/ReformattedPredictions/Savant_PBMC2NormMix_LM22-Stromal.tsv > NormedPredictions/Savant_PBMC2NormMix_LM22-Stromal.tsv
python B_NormFile.py ../2ReformatPredictions/ReformattedPredictions/Savant_PBMC2NormMix_SkinSigs.tsv > NormedPredictions/Savant_PBMC2NormMix_SkinSigs.tsv
python B_NormFile.py ../2ReformatPredictions/ReformattedPredictions/Savant_StromalNormMix_10xSigs.tsv > NormedPredictions/Savant_StromalNormMix_10xSigs.tsv
python B_NormFile.py ../2ReformatPredictions/ReformattedPredictions/Savant_StromalNormMix_BlueCode.tsv > NormedPredictions/Savant_StromalNormMix_BlueCode.tsv
python B_NormFile.py ../2ReformatPredictions/ReformattedPredictions/Savant_StromalNormMix_BluePrint-Blood.tsv > NormedPredictions/Savant_StromalNormMix_BluePrint-Blood.tsv
python B_NormFile.py ../2ReformatPredictions/ReformattedPredictions/Savant_StromalNormMix_EPIC-BCIC.tsv > NormedPredictions/Savant_StromalNormMix_EPIC-BCIC.tsv
python B_NormFile.py ../2ReformatPredictions/ReformattedPredictions/Savant_StromalNormMix_EPIC-TIC.tsv > NormedPredictions/Savant_StromalNormMix_EPIC-TIC.tsv
python B_NormFile.py ../2ReformatPredictions/ReformattedPredictions/Savant_StromalNormMix_HPCA-Blood.tsv > NormedPredictions/Savant_StromalNormMix_HPCA-Blood.tsv
python B_NormFile.py ../2ReformatPredictions/ReformattedPredictions/Savant_StromalNormMix_HPCA-Stromal.tsv > NormedPredictions/Savant_StromalNormMix_HPCA-Stromal.tsv
python B_NormFile.py ../2ReformatPredictions/ReformattedPredictions/Savant_StromalNormMix_ImmuneCellSignatures.tsv > NormedPredictions/Savant_StromalNormMix_ImmuneCellSignatures.tsv
python B_NormFile.py ../2ReformatPredictions/ReformattedPredictions/Savant_StromalNormMix_ImmunoStates-Blood.tsv > NormedPredictions/Savant_StromalNormMix_ImmunoStates-Blood.tsv
python B_NormFile.py ../2ReformatPredictions/ReformattedPredictions/Savant_StromalNormMix_ImmunoStates-Full.tsv > NormedPredictions/Savant_StromalNormMix_ImmunoStates-Full.tsv
python B_NormFile.py ../2ReformatPredictions/ReformattedPredictions/Savant_StromalNormMix_ImmunoStates-Stromal.tsv > NormedPredictions/Savant_StromalNormMix_ImmunoStates-Stromal.tsv
python B_NormFile.py ../2ReformatPredictions/ReformattedPredictions/Savant_StromalNormMix_LM22-Blood.tsv > NormedPredictions/Savant_StromalNormMix_LM22-Blood.tsv
python B_NormFile.py ../2ReformatPredictions/ReformattedPredictions/Savant_StromalNormMix_LM22-Full.tsv > NormedPredictions/Savant_StromalNormMix_LM22-Full.tsv
python B_NormFile.py ../2ReformatPredictions/ReformattedPredictions/Savant_StromalNormMix_LM22-Stromal.tsv > NormedPredictions/Savant_StromalNormMix_LM22-Stromal.tsv
python B_NormFile.py ../2ReformatPredictions/ReformattedPredictions/Savant_StromalNormMix_SkinSigs.tsv > NormedPredictions/Savant_StromalNormMix_SkinSigs.tsv
python B_NormFile.py ../2ReformatPredictions/ReformattedPredictions/cibersort_CellMix_BluePrint-Blood.tsv > NormedPredictions/cibersort_CellMix_BluePrint-Blood.tsv
python B_NormFile.py ../2ReformatPredictions/ReformattedPredictions/cibersort_CellMix_EPIC-BCIC.tsv > NormedPredictions/cibersort_CellMix_EPIC-BCIC.tsv
python B_NormFile.py ../2ReformatPredictions/ReformattedPredictions/cibersort_CellMix_HPCA-Blood.tsv > NormedPredictions/cibersort_CellMix_HPCA-Blood.tsv
python B_NormFile.py ../2ReformatPredictions/ReformattedPredictions/cibersort_CellMix_ImmunoStates-Blood.tsv > NormedPredictions/cibersort_CellMix_ImmunoStates-Blood.tsv
python B_NormFile.py ../2ReformatPredictions/ReformattedPredictions/cibersort_CellMix_ImmunoStates-Full.tsv > NormedPredictions/cibersort_CellMix_ImmunoStates-Full.tsv
python B_NormFile.py ../2ReformatPredictions/ReformattedPredictions/cibersort_CellMix_LM22-Blood.tsv > NormedPredictions/cibersort_CellMix_LM22-Blood.tsv
python B_NormFile.py ../2ReformatPredictions/ReformattedPredictions/cibersort_CellMix_LM22-Full.tsv > NormedPredictions/cibersort_CellMix_LM22-Full.tsv
python B_NormFile.py ../2ReformatPredictions/ReformattedPredictions/cibersort_PBMC1NormMix_BluePrint-Blood.tsv > NormedPredictions/cibersort_PBMC1NormMix_BluePrint-Blood.tsv
python B_NormFile.py ../2ReformatPredictions/ReformattedPredictions/cibersort_PBMC1NormMix_EPIC-BCIC.tsv > NormedPredictions/cibersort_PBMC1NormMix_EPIC-BCIC.tsv
python B_NormFile.py ../2ReformatPredictions/ReformattedPredictions/cibersort_PBMC1NormMix_HPCA-Blood.tsv > NormedPredictions/cibersort_PBMC1NormMix_HPCA-Blood.tsv
python B_NormFile.py ../2ReformatPredictions/ReformattedPredictions/cibersort_PBMC1NormMix_ImmunoStates-Blood.tsv > NormedPredictions/cibersort_PBMC1NormMix_ImmunoStates-Blood.tsv
python B_NormFile.py ../2ReformatPredictions/ReformattedPredictions/cibersort_PBMC1NormMix_ImmunoStates-Full.tsv > NormedPredictions/cibersort_PBMC1NormMix_ImmunoStates-Full.tsv
python B_NormFile.py ../2ReformatPredictions/ReformattedPredictions/cibersort_PBMC1NormMix_LM22-Blood.tsv > NormedPredictions/cibersort_PBMC1NormMix_LM22-Blood.tsv
python B_NormFile.py ../2ReformatPredictions/ReformattedPredictions/cibersort_PBMC1NormMix_LM22-Full.tsv > NormedPredictions/cibersort_PBMC1NormMix_LM22-Full.tsv
python B_NormFile.py ../2ReformatPredictions/ReformattedPredictions/cibersort_PBMC2NormMix_BluePrint-Blood.tsv > NormedPredictions/cibersort_PBMC2NormMix_BluePrint-Blood.tsv
python B_NormFile.py ../2ReformatPredictions/ReformattedPredictions/cibersort_PBMC2NormMix_EPIC-BCIC.tsv > NormedPredictions/cibersort_PBMC2NormMix_EPIC-BCIC.tsv
python B_NormFile.py ../2ReformatPredictions/ReformattedPredictions/cibersort_PBMC2NormMix_HPCA-Blood.tsv > NormedPredictions/cibersort_PBMC2NormMix_HPCA-Blood.tsv
python B_NormFile.py ../2ReformatPredictions/ReformattedPredictions/cibersort_PBMC2NormMix_ImmunoStates-Blood.tsv > NormedPredictions/cibersort_PBMC2NormMix_ImmunoStates-Blood.tsv
python B_NormFile.py ../2ReformatPredictions/ReformattedPredictions/cibersort_PBMC2NormMix_ImmunoStates-Full.tsv > NormedPredictions/cibersort_PBMC2NormMix_ImmunoStates-Full.tsv
python B_NormFile.py ../2ReformatPredictions/ReformattedPredictions/cibersort_PBMC2NormMix_LM22-Blood.tsv > NormedPredictions/cibersort_PBMC2NormMix_LM22-Blood.tsv
python B_NormFile.py ../2ReformatPredictions/ReformattedPredictions/cibersort_PBMC2NormMix_LM22-Full.tsv > NormedPredictions/cibersort_PBMC2NormMix_LM22-Full.tsv
python B_NormFile.py ../2ReformatPredictions/ReformattedPredictions/cibersort_StromalNormMix_BluePrint-Blood.tsv > NormedPredictions/cibersort_StromalNormMix_BluePrint-Blood.tsv
python B_NormFile.py ../2ReformatPredictions/ReformattedPredictions/cibersort_StromalNormMix_EPIC-BCIC.tsv > NormedPredictions/cibersort_StromalNormMix_EPIC-BCIC.tsv
python B_NormFile.py ../2ReformatPredictions/ReformattedPredictions/cibersort_StromalNormMix_EPIC-TIC.tsv > NormedPredictions/cibersort_StromalNormMix_EPIC-TIC.tsv
python B_NormFile.py ../2ReformatPredictions/ReformattedPredictions/cibersort_StromalNormMix_HPCA-Blood.tsv > NormedPredictions/cibersort_StromalNormMix_HPCA-Blood.tsv
python B_NormFile.py ../2ReformatPredictions/ReformattedPredictions/cibersort_StromalNormMix_HPCA-StromalReference.tsv > NormedPredictions/cibersort_StromalNormMix_HPCA-StromalReference.tsv
python B_NormFile.py ../2ReformatPredictions/ReformattedPredictions/cibersort_StromalNormMix_ImmunoStates-Blood.tsv > NormedPredictions/cibersort_StromalNormMix_ImmunoStates-Blood.tsv
python B_NormFile.py ../2ReformatPredictions/ReformattedPredictions/cibersort_StromalNormMix_ImmunoStates-Full.tsv > NormedPredictions/cibersort_StromalNormMix_ImmunoStates-Full.tsv
python B_NormFile.py ../2ReformatPredictions/ReformattedPredictions/cibersort_StromalNormMix_ImmunoStates-Stromal.tsv > NormedPredictions/cibersort_StromalNormMix_ImmunoStates-Stromal.tsv
python B_NormFile.py ../2ReformatPredictions/ReformattedPredictions/cibersort_StromalNormMix_LM22-Blood.tsv > NormedPredictions/cibersort_StromalNormMix_LM22-Blood.tsv
python B_NormFile.py ../2ReformatPredictions/ReformattedPredictions/cibersort_StromalNormMix_LM22-Full.tsv > NormedPredictions/cibersort_StromalNormMix_LM22-Full.tsv
python B_NormFile.py ../2ReformatPredictions/ReformattedPredictions/cibersort_StromalNormMix_LM22-Stromal.tsv > NormedPredictions/cibersort_StromalNormMix_LM22-Stromal.tsv
python B_NormFile.py ../2ReformatPredictions/ReformattedPredictions/dtangle_CellMixtures_10XImmune.tsv > NormedPredictions/dtangle_CellMixtures_10XImmune.tsv
python B_NormFile.py ../2ReformatPredictions/ReformattedPredictions/dtangle_CellMixtures_BlueCodeV1.tsv > NormedPredictions/dtangle_CellMixtures_BlueCodeV1.tsv
python B_NormFile.py ../2ReformatPredictions/ReformattedPredictions/dtangle_CellMixtures_BluePrint-Blood.tsv > NormedPredictions/dtangle_CellMixtures_BluePrint-Blood.tsv
python B_NormFile.py ../2ReformatPredictions/ReformattedPredictions/dtangle_CellMixtures_EPIC-BCIC.tsv > NormedPredictions/dtangle_CellMixtures_EPIC-BCIC.tsv
python B_NormFile.py ../2ReformatPredictions/ReformattedPredictions/dtangle_CellMixtures_EPIC-TIC.tsv > NormedPredictions/dtangle_CellMixtures_EPIC-TIC.tsv
python B_NormFile.py ../2ReformatPredictions/ReformattedPredictions/dtangle_CellMixtures_HPCA-Blood.tsv > NormedPredictions/dtangle_CellMixtures_HPCA-Blood.tsv
python B_NormFile.py ../2ReformatPredictions/ReformattedPredictions/dtangle_CellMixtures_HPCA-Stromal.tsv > NormedPredictions/dtangle_CellMixtures_HPCA-Stromal.tsv
python B_NormFile.py ../2ReformatPredictions/ReformattedPredictions/dtangle_CellMixtures_ImmunoStates-Blood.tsv > NormedPredictions/dtangle_CellMixtures_ImmunoStates-Blood.tsv
python B_NormFile.py ../2ReformatPredictions/ReformattedPredictions/dtangle_CellMixtures_ImmunoStates-Full.tsv > NormedPredictions/dtangle_CellMixtures_ImmunoStates-Full.tsv
python B_NormFile.py ../2ReformatPredictions/ReformattedPredictions/dtangle_CellMixtures_ImmunoStates-Stromal.tsv > NormedPredictions/dtangle_CellMixtures_ImmunoStates-Stromal.tsv
python B_NormFile.py ../2ReformatPredictions/ReformattedPredictions/dtangle_CellMixtures_LM22-Blood.tsv > NormedPredictions/dtangle_CellMixtures_LM22-Blood.tsv
python B_NormFile.py ../2ReformatPredictions/ReformattedPredictions/dtangle_CellMixtures_LM22-Full.tsv > NormedPredictions/dtangle_CellMixtures_LM22-Full.tsv
python B_NormFile.py ../2ReformatPredictions/ReformattedPredictions/dtangle_CellMixtures_LM22-Stromal.tsv > NormedPredictions/dtangle_CellMixtures_LM22-Stromal.tsv
python B_NormFile.py ../2ReformatPredictions/ReformattedPredictions/dtangle_CellMixtures_SkinSignaturesV1.tsv > NormedPredictions/dtangle_CellMixtures_SkinSignaturesV1.tsv
python B_NormFile.py ../2ReformatPredictions/ReformattedPredictions/dtangle_Fram_10XImmune.tsv > NormedPredictions/dtangle_Fram_10XImmune.tsv
python B_NormFile.py ../2ReformatPredictions/ReformattedPredictions/dtangle_Fram_BlueCodeV1.tsv > NormedPredictions/dtangle_Fram_BlueCodeV1.tsv
python B_NormFile.py ../2ReformatPredictions/ReformattedPredictions/dtangle_Fram_BluePrint-Blood.tsv > NormedPredictions/dtangle_Fram_BluePrint-Blood.tsv
python B_NormFile.py ../2ReformatPredictions/ReformattedPredictions/dtangle_Fram_EPIC-BCIC.tsv > NormedPredictions/dtangle_Fram_EPIC-BCIC.tsv
python B_NormFile.py ../2ReformatPredictions/ReformattedPredictions/dtangle_Fram_EPIC-TIC.tsv > NormedPredictions/dtangle_Fram_EPIC-TIC.tsv
python B_NormFile.py ../2ReformatPredictions/ReformattedPredictions/dtangle_Fram_HPCA-Blood.tsv > NormedPredictions/dtangle_Fram_HPCA-Blood.tsv
python B_NormFile.py ../2ReformatPredictions/ReformattedPredictions/dtangle_Fram_HPCA-Stromal.tsv > NormedPredictions/dtangle_Fram_HPCA-Stromal.tsv
python B_NormFile.py ../2ReformatPredictions/ReformattedPredictions/dtangle_Fram_ImmunoStates-Blood.tsv > NormedPredictions/dtangle_Fram_ImmunoStates-Blood.tsv
python B_NormFile.py ../2ReformatPredictions/ReformattedPredictions/dtangle_Fram_ImmunoStates-Full.tsv > NormedPredictions/dtangle_Fram_ImmunoStates-Full.tsv
python B_NormFile.py ../2ReformatPredictions/ReformattedPredictions/dtangle_Fram_ImmunoStates-Stromal.tsv > NormedPredictions/dtangle_Fram_ImmunoStates-Stromal.tsv
python B_NormFile.py ../2ReformatPredictions/ReformattedPredictions/dtangle_Fram_LM22-Blood.tsv > NormedPredictions/dtangle_Fram_LM22-Blood.tsv
python B_NormFile.py ../2ReformatPredictions/ReformattedPredictions/dtangle_Fram_LM22-Full.tsv > NormedPredictions/dtangle_Fram_LM22-Full.tsv
python B_NormFile.py ../2ReformatPredictions/ReformattedPredictions/dtangle_Fram_LM22-Stromal.tsv > NormedPredictions/dtangle_Fram_LM22-Stromal.tsv
python B_NormFile.py ../2ReformatPredictions/ReformattedPredictions/dtangle_Fram_SkinSignaturesV1.tsv > NormedPredictions/dtangle_Fram_SkinSignaturesV1.tsv
python B_NormFile.py ../2ReformatPredictions/ReformattedPredictions/dtangle_PBMC1NormMix_10XImmune.tsv > NormedPredictions/dtangle_PBMC1NormMix_10XImmune.tsv
python B_NormFile.py ../2ReformatPredictions/ReformattedPredictions/dtangle_PBMC1NormMix_BlueCodeV1.tsv > NormedPredictions/dtangle_PBMC1NormMix_BlueCodeV1.tsv
python B_NormFile.py ../2ReformatPredictions/ReformattedPredictions/dtangle_PBMC1NormMix_BluePrint-Blood.tsv > NormedPredictions/dtangle_PBMC1NormMix_BluePrint-Blood.tsv
python B_NormFile.py ../2ReformatPredictions/ReformattedPredictions/dtangle_PBMC1NormMix_EPIC-BCIC.tsv > NormedPredictions/dtangle_PBMC1NormMix_EPIC-BCIC.tsv
python B_NormFile.py ../2ReformatPredictions/ReformattedPredictions/dtangle_PBMC1NormMix_EPIC-TIC.tsv > NormedPredictions/dtangle_PBMC1NormMix_EPIC-TIC.tsv
python B_NormFile.py ../2ReformatPredictions/ReformattedPredictions/dtangle_PBMC1NormMix_HPCA-Blood.tsv > NormedPredictions/dtangle_PBMC1NormMix_HPCA-Blood.tsv
python B_NormFile.py ../2ReformatPredictions/ReformattedPredictions/dtangle_PBMC1NormMix_HPCA-Stromal.tsv > NormedPredictions/dtangle_PBMC1NormMix_HPCA-Stromal.tsv
python B_NormFile.py ../2ReformatPredictions/ReformattedPredictions/dtangle_PBMC1NormMix_ImmunoStates-Blood.tsv > NormedPredictions/dtangle_PBMC1NormMix_ImmunoStates-Blood.tsv
python B_NormFile.py ../2ReformatPredictions/ReformattedPredictions/dtangle_PBMC1NormMix_ImmunoStates-Full.tsv > NormedPredictions/dtangle_PBMC1NormMix_ImmunoStates-Full.tsv
python B_NormFile.py ../2ReformatPredictions/ReformattedPredictions/dtangle_PBMC1NormMix_ImmunoStates-Stromal.tsv > NormedPredictions/dtangle_PBMC1NormMix_ImmunoStates-Stromal.tsv
python B_NormFile.py ../2ReformatPredictions/ReformattedPredictions/dtangle_PBMC1NormMix_LM22-Blood.tsv > NormedPredictions/dtangle_PBMC1NormMix_LM22-Blood.tsv
python B_NormFile.py ../2ReformatPredictions/ReformattedPredictions/dtangle_PBMC1NormMix_LM22-Full.tsv > NormedPredictions/dtangle_PBMC1NormMix_LM22-Full.tsv
python B_NormFile.py ../2ReformatPredictions/ReformattedPredictions/dtangle_PBMC1NormMix_LM22-Stromal.tsv > NormedPredictions/dtangle_PBMC1NormMix_LM22-Stromal.tsv
python B_NormFile.py ../2ReformatPredictions/ReformattedPredictions/dtangle_PBMC1NormMix_SkinSignaturesV1.tsv > NormedPredictions/dtangle_PBMC1NormMix_SkinSignaturesV1.tsv
python B_NormFile.py ../2ReformatPredictions/ReformattedPredictions/dtangle_PBMC2NormMix_10XImmune.tsv > NormedPredictions/dtangle_PBMC2NormMix_10XImmune.tsv
python B_NormFile.py ../2ReformatPredictions/ReformattedPredictions/dtangle_PBMC2NormMix_BlueCodeV1.tsv > NormedPredictions/dtangle_PBMC2NormMix_BlueCodeV1.tsv
python B_NormFile.py ../2ReformatPredictions/ReformattedPredictions/dtangle_PBMC2NormMix_BluePrint-Blood.tsv > NormedPredictions/dtangle_PBMC2NormMix_BluePrint-Blood.tsv
python B_NormFile.py ../2ReformatPredictions/ReformattedPredictions/dtangle_PBMC2NormMix_EPIC-BCIC.tsv > NormedPredictions/dtangle_PBMC2NormMix_EPIC-BCIC.tsv
python B_NormFile.py ../2ReformatPredictions/ReformattedPredictions/dtangle_PBMC2NormMix_EPIC-TIC.tsv > NormedPredictions/dtangle_PBMC2NormMix_EPIC-TIC.tsv
python B_NormFile.py ../2ReformatPredictions/ReformattedPredictions/dtangle_PBMC2NormMix_HPCA-Blood.tsv > NormedPredictions/dtangle_PBMC2NormMix_HPCA-Blood.tsv
python B_NormFile.py ../2ReformatPredictions/ReformattedPredictions/dtangle_PBMC2NormMix_HPCA-Stromal.tsv > NormedPredictions/dtangle_PBMC2NormMix_HPCA-Stromal.tsv
python B_NormFile.py ../2ReformatPredictions/ReformattedPredictions/dtangle_PBMC2NormMix_ImmunoStates-Blood.tsv > NormedPredictions/dtangle_PBMC2NormMix_ImmunoStates-Blood.tsv
python B_NormFile.py ../2ReformatPredictions/ReformattedPredictions/dtangle_PBMC2NormMix_ImmunoStates-Full.tsv > NormedPredictions/dtangle_PBMC2NormMix_ImmunoStates-Full.tsv
python B_NormFile.py ../2ReformatPredictions/ReformattedPredictions/dtangle_PBMC2NormMix_ImmunoStates-Stromal.tsv > NormedPredictions/dtangle_PBMC2NormMix_ImmunoStates-Stromal.tsv
python B_NormFile.py ../2ReformatPredictions/ReformattedPredictions/dtangle_PBMC2NormMix_LM22-Blood.tsv > NormedPredictions/dtangle_PBMC2NormMix_LM22-Blood.tsv
python B_NormFile.py ../2ReformatPredictions/ReformattedPredictions/dtangle_PBMC2NormMix_LM22-Full.tsv > NormedPredictions/dtangle_PBMC2NormMix_LM22-Full.tsv
python B_NormFile.py ../2ReformatPredictions/ReformattedPredictions/dtangle_PBMC2NormMix_LM22-Stromal.tsv > NormedPredictions/dtangle_PBMC2NormMix_LM22-Stromal.tsv
python B_NormFile.py ../2ReformatPredictions/ReformattedPredictions/dtangle_PBMC2NormMix_SkinSignaturesV1.tsv > NormedPredictions/dtangle_PBMC2NormMix_SkinSignaturesV1.tsv
python B_NormFile.py ../2ReformatPredictions/ReformattedPredictions/dtangle_StromalNormMix_10XImmune.tsv > NormedPredictions/dtangle_StromalNormMix_10XImmune.tsv
python B_NormFile.py ../2ReformatPredictions/ReformattedPredictions/dtangle_StromalNormMix_BlueCodeV1.tsv > NormedPredictions/dtangle_StromalNormMix_BlueCodeV1.tsv
python B_NormFile.py ../2ReformatPredictions/ReformattedPredictions/dtangle_StromalNormMix_BluePrint-Blood.tsv > NormedPredictions/dtangle_StromalNormMix_BluePrint-Blood.tsv
python B_NormFile.py ../2ReformatPredictions/ReformattedPredictions/dtangle_StromalNormMix_EPIC-BCIC.tsv > NormedPredictions/dtangle_StromalNormMix_EPIC-BCIC.tsv
python B_NormFile.py ../2ReformatPredictions/ReformattedPredictions/dtangle_StromalNormMix_EPIC-TIC.tsv > NormedPredictions/dtangle_StromalNormMix_EPIC-TIC.tsv
python B_NormFile.py ../2ReformatPredictions/ReformattedPredictions/dtangle_StromalNormMix_HPCA-Blood.tsv > NormedPredictions/dtangle_StromalNormMix_HPCA-Blood.tsv
python B_NormFile.py ../2ReformatPredictions/ReformattedPredictions/dtangle_StromalNormMix_HPCA-Stromal.tsv > NormedPredictions/dtangle_StromalNormMix_HPCA-Stromal.tsv
python B_NormFile.py ../2ReformatPredictions/ReformattedPredictions/dtangle_StromalNormMix_ImmunoStates-Blood.tsv > NormedPredictions/dtangle_StromalNormMix_ImmunoStates-Blood.tsv
python B_NormFile.py ../2ReformatPredictions/ReformattedPredictions/dtangle_StromalNormMix_ImmunoStates-Full.tsv > NormedPredictions/dtangle_StromalNormMix_ImmunoStates-Full.tsv
python B_NormFile.py ../2ReformatPredictions/ReformattedPredictions/dtangle_StromalNormMix_ImmunoStates-Stromal.tsv > NormedPredictions/dtangle_StromalNormMix_ImmunoStates-Stromal.tsv
python B_NormFile.py ../2ReformatPredictions/ReformattedPredictions/dtangle_StromalNormMix_LM22-Blood.tsv > NormedPredictions/dtangle_StromalNormMix_LM22-Blood.tsv
python B_NormFile.py ../2ReformatPredictions/ReformattedPredictions/dtangle_StromalNormMix_LM22-Full.tsv > NormedPredictions/dtangle_StromalNormMix_LM22-Full.tsv
python B_NormFile.py ../2ReformatPredictions/ReformattedPredictions/dtangle_StromalNormMix_LM22-Stromal.tsv > NormedPredictions/dtangle_StromalNormMix_LM22-Stromal.tsv
python B_NormFile.py ../2ReformatPredictions/ReformattedPredictions/dtangle_StromalNormMix_SkinSignaturesV1.tsv > NormedPredictions/dtangle_StromalNormMix_SkinSignaturesV1.tsv
python B_NormFile.py ../2ReformatPredictions/ReformattedPredictions/xCell_CellMixtures_xCell.tsv > NormedPredictions/xCell_CellMixtures_xCell.tsv
python B_NormFile.py ../2ReformatPredictions/ReformattedPredictions/xCell_PBMC1NormMix_xCell.tsv > NormedPredictions/xCell_PBMC1NormMix_xCell.tsv
python B_NormFile.py ../2ReformatPredictions/ReformattedPredictions/xCell_PBMC2NormMix_xCell.tsv > NormedPredictions/xCell_PBMC2NormMix_xCell.tsv
python B_NormFile.py ../2ReformatPredictions/ReformattedPredictions/xCell_StromalNormMix_xCel2l.tsv > NormedPredictions/xCell_StromalNormMix_xCel2l.tsv
python B_NormFile.py ../2ReformatPredictions/ReformattedPredictions/xCell_StromalNormMix_xCell.tsv > NormedPredictions/xCell_StromalNormMix_xCell.tsv
