./WrapperDCQ.sh /u/home/b/bnadel/Benchmarking/Inputs/Mixes/CellMixtures.tsv /u/home/b/bnadel/Benchmarking/Inputs/RefMats/10XImmune.tsv predictions/DCQ_CellMixtures_10XImmune.tsv
./WrapperDCQ.sh /u/home/b/bnadel/Benchmarking/Inputs/Mixes/CellMixtures.tsv /u/home/b/bnadel/Benchmarking/Inputs/RefMats/BlueCodeV1.0.tsv predictions/DCQ_CellMixtures_BlueCodeV1.tsv
./WrapperDCQ.sh /u/home/b/bnadel/Benchmarking/Inputs/Mixes/CellMixtures.tsv /u/home/b/bnadel/Benchmarking/Inputs/RefMats/BluePrint-Blood.tsv predictions/DCQ_CellMixtures_BluePrint-Blood.tsv
./WrapperDCQ.sh /u/home/b/bnadel/Benchmarking/Inputs/Mixes/CellMixtures.tsv /u/home/b/bnadel/Benchmarking/Inputs/RefMats/EPIC-BCIC.tsv predictions/DCQ_CellMixtures_EPIC-BCIC.tsv
./WrapperDCQ.sh /u/home/b/bnadel/Benchmarking/Inputs/Mixes/CellMixtures.tsv /u/home/b/bnadel/Benchmarking/Inputs/RefMats/EPIC-TIC.tsv predictions/DCQ_CellMixtures_EPIC-TIC.tsv
./WrapperDCQ.sh /u/home/b/bnadel/Benchmarking/Inputs/Mixes/CellMixtures.tsv /u/home/b/bnadel/Benchmarking/Inputs/RefMats/HPCA-Blood.tsv predictions/DCQ_CellMixtures_HPCA-Blood.tsv
./WrapperDCQ.sh /u/home/b/bnadel/Benchmarking/Inputs/Mixes/CellMixtures.tsv /u/home/b/bnadel/Benchmarking/Inputs/RefMats/HPCA-Stromal.tsv predictions/DCQ_CellMixtures_HPCA-Stromal.tsv
./WrapperDCQ.sh /u/home/b/bnadel/Benchmarking/Inputs/Mixes/CellMixtures.tsv /u/home/b/bnadel/Benchmarking/Inputs/RefMats/ImmunoStates-Blood.tsv predictions/DCQ_CellMixtures_ImmunoStates-Blood.tsv
./WrapperDCQ.sh /u/home/b/bnadel/Benchmarking/Inputs/Mixes/CellMixtures.tsv /u/home/b/bnadel/Benchmarking/Inputs/RefMats/ImmunoStates-Full.tsv predictions/DCQ_CellMixtures_ImmunoStates-Full.tsv
./WrapperDCQ.sh /u/home/b/bnadel/Benchmarking/Inputs/Mixes/CellMixtures.tsv /u/home/b/bnadel/Benchmarking/Inputs/RefMats/ImmunoStates-Stromal.tsv predictions/DCQ_CellMixtures_ImmunoStates-Stromal.tsv
./WrapperDCQ.sh /u/home/b/bnadel/Benchmarking/Inputs/Mixes/CellMixtures.tsv /u/home/b/bnadel/Benchmarking/Inputs/RefMats/LM22-Blood.tsv predictions/DCQ_CellMixtures_LM22-Blood.tsv
./WrapperDCQ.sh /u/home/b/bnadel/Benchmarking/Inputs/Mixes/CellMixtures.tsv /u/home/b/bnadel/Benchmarking/Inputs/RefMats/LM22-Full.tsv predictions/DCQ_CellMixtures_LM22-Full.tsv
./WrapperDCQ.sh /u/home/b/bnadel/Benchmarking/Inputs/Mixes/CellMixtures.tsv /u/home/b/bnadel/Benchmarking/Inputs/RefMats/LM22-Stromal.tsv predictions/DCQ_CellMixtures_LM22-Stromal.tsv
./WrapperDCQ.sh /u/home/b/bnadel/Benchmarking/Inputs/Mixes/CellMixtures.tsv /u/home/b/bnadel/Benchmarking/Inputs/RefMats/SkinSignaturesV1.0.tsv predictions/DCQ_CellMixtures_SkinSignaturesV1.tsv
./WrapperDCQ.sh /u/home/b/bnadel/Benchmarking/Inputs/Mixes/Fram.tsv /u/home/b/bnadel/Benchmarking/Inputs/RefMats/10XImmune.tsv predictions/DCQ_Fram_10XImmune.tsv
./WrapperDCQ.sh /u/home/b/bnadel/Benchmarking/Inputs/Mixes/Fram.tsv /u/home/b/bnadel/Benchmarking/Inputs/RefMats/BlueCodeV1.0.tsv predictions/DCQ_Fram_BlueCodeV1.tsv
./WrapperDCQ.sh /u/home/b/bnadel/Benchmarking/Inputs/Mixes/Fram.tsv /u/home/b/bnadel/Benchmarking/Inputs/RefMats/BluePrint-Blood.tsv predictions/DCQ_Fram_BluePrint-Blood.tsv
./WrapperDCQ.sh /u/home/b/bnadel/Benchmarking/Inputs/Mixes/Fram.tsv /u/home/b/bnadel/Benchmarking/Inputs/RefMats/EPIC-BCIC.tsv predictions/DCQ_Fram_EPIC-BCIC.tsv
./WrapperDCQ.sh /u/home/b/bnadel/Benchmarking/Inputs/Mixes/Fram.tsv /u/home/b/bnadel/Benchmarking/Inputs/RefMats/EPIC-TIC.tsv predictions/DCQ_Fram_EPIC-TIC.tsv
./WrapperDCQ.sh /u/home/b/bnadel/Benchmarking/Inputs/Mixes/Fram.tsv /u/home/b/bnadel/Benchmarking/Inputs/RefMats/HPCA-Blood.tsv predictions/DCQ_Fram_HPCA-Blood.tsv
./WrapperDCQ.sh /u/home/b/bnadel/Benchmarking/Inputs/Mixes/Fram.tsv /u/home/b/bnadel/Benchmarking/Inputs/RefMats/HPCA-Stromal.tsv predictions/DCQ_Fram_HPCA-Stromal.tsv
./WrapperDCQ.sh /u/home/b/bnadel/Benchmarking/Inputs/Mixes/Fram.tsv /u/home/b/bnadel/Benchmarking/Inputs/RefMats/ImmunoStates-Blood.tsv predictions/DCQ_Fram_ImmunoStates-Blood.tsv
./WrapperDCQ.sh /u/home/b/bnadel/Benchmarking/Inputs/Mixes/Fram.tsv /u/home/b/bnadel/Benchmarking/Inputs/RefMats/ImmunoStates-Full.tsv predictions/DCQ_Fram_ImmunoStates-Full.tsv
./WrapperDCQ.sh /u/home/b/bnadel/Benchmarking/Inputs/Mixes/Fram.tsv /u/home/b/bnadel/Benchmarking/Inputs/RefMats/ImmunoStates-Stromal.tsv predictions/DCQ_Fram_ImmunoStates-Stromal.tsv
./WrapperDCQ.sh /u/home/b/bnadel/Benchmarking/Inputs/Mixes/Fram.tsv /u/home/b/bnadel/Benchmarking/Inputs/RefMats/LM22-Blood.tsv predictions/DCQ_Fram_LM22-Blood.tsv
./WrapperDCQ.sh /u/home/b/bnadel/Benchmarking/Inputs/Mixes/Fram.tsv /u/home/b/bnadel/Benchmarking/Inputs/RefMats/LM22-Full.tsv predictions/DCQ_Fram_LM22-Full.tsv
./WrapperDCQ.sh /u/home/b/bnadel/Benchmarking/Inputs/Mixes/Fram.tsv /u/home/b/bnadel/Benchmarking/Inputs/RefMats/LM22-Stromal.tsv predictions/DCQ_Fram_LM22-Stromal.tsv
./WrapperDCQ.sh /u/home/b/bnadel/Benchmarking/Inputs/Mixes/Fram.tsv /u/home/b/bnadel/Benchmarking/Inputs/RefMats/SkinSignaturesV1.0.tsv predictions/DCQ_Fram_SkinSignaturesV1.tsv
./WrapperDCQ.sh /u/home/b/bnadel/Benchmarking/Inputs/Mixes/PBMC1NormMix.tsv /u/home/b/bnadel/Benchmarking/Inputs/RefMats/10XImmune.tsv predictions/DCQ_PBMC1NormMix_10XImmune.tsv
./WrapperDCQ.sh /u/home/b/bnadel/Benchmarking/Inputs/Mixes/PBMC1NormMix.tsv /u/home/b/bnadel/Benchmarking/Inputs/RefMats/BlueCodeV1.0.tsv predictions/DCQ_PBMC1NormMix_BlueCodeV1.tsv
./WrapperDCQ.sh /u/home/b/bnadel/Benchmarking/Inputs/Mixes/PBMC1NormMix.tsv /u/home/b/bnadel/Benchmarking/Inputs/RefMats/BluePrint-Blood.tsv predictions/DCQ_PBMC1NormMix_BluePrint-Blood.tsv
./WrapperDCQ.sh /u/home/b/bnadel/Benchmarking/Inputs/Mixes/PBMC1NormMix.tsv /u/home/b/bnadel/Benchmarking/Inputs/RefMats/EPIC-BCIC.tsv predictions/DCQ_PBMC1NormMix_EPIC-BCIC.tsv
./WrapperDCQ.sh /u/home/b/bnadel/Benchmarking/Inputs/Mixes/PBMC1NormMix.tsv /u/home/b/bnadel/Benchmarking/Inputs/RefMats/EPIC-TIC.tsv predictions/DCQ_PBMC1NormMix_EPIC-TIC.tsv
./WrapperDCQ.sh /u/home/b/bnadel/Benchmarking/Inputs/Mixes/PBMC1NormMix.tsv /u/home/b/bnadel/Benchmarking/Inputs/RefMats/HPCA-Blood.tsv predictions/DCQ_PBMC1NormMix_HPCA-Blood.tsv
./WrapperDCQ.sh /u/home/b/bnadel/Benchmarking/Inputs/Mixes/PBMC1NormMix.tsv /u/home/b/bnadel/Benchmarking/Inputs/RefMats/HPCA-Stromal.tsv predictions/DCQ_PBMC1NormMix_HPCA-Stromal.tsv
./WrapperDCQ.sh /u/home/b/bnadel/Benchmarking/Inputs/Mixes/PBMC1NormMix.tsv /u/home/b/bnadel/Benchmarking/Inputs/RefMats/ImmunoStates-Blood.tsv predictions/DCQ_PBMC1NormMix_ImmunoStates-Blood.tsv
./WrapperDCQ.sh /u/home/b/bnadel/Benchmarking/Inputs/Mixes/PBMC1NormMix.tsv /u/home/b/bnadel/Benchmarking/Inputs/RefMats/ImmunoStates-Full.tsv predictions/DCQ_PBMC1NormMix_ImmunoStates-Full.tsv
./WrapperDCQ.sh /u/home/b/bnadel/Benchmarking/Inputs/Mixes/PBMC1NormMix.tsv /u/home/b/bnadel/Benchmarking/Inputs/RefMats/ImmunoStates-Stromal.tsv predictions/DCQ_PBMC1NormMix_ImmunoStates-Stromal.tsv
./WrapperDCQ.sh /u/home/b/bnadel/Benchmarking/Inputs/Mixes/PBMC1NormMix.tsv /u/home/b/bnadel/Benchmarking/Inputs/RefMats/LM22-Blood.tsv predictions/DCQ_PBMC1NormMix_LM22-Blood.tsv
./WrapperDCQ.sh /u/home/b/bnadel/Benchmarking/Inputs/Mixes/PBMC1NormMix.tsv /u/home/b/bnadel/Benchmarking/Inputs/RefMats/LM22-Full.tsv predictions/DCQ_PBMC1NormMix_LM22-Full.tsv
./WrapperDCQ.sh /u/home/b/bnadel/Benchmarking/Inputs/Mixes/PBMC1NormMix.tsv /u/home/b/bnadel/Benchmarking/Inputs/RefMats/LM22-Stromal.tsv predictions/DCQ_PBMC1NormMix_LM22-Stromal.tsv
./WrapperDCQ.sh /u/home/b/bnadel/Benchmarking/Inputs/Mixes/PBMC1NormMix.tsv /u/home/b/bnadel/Benchmarking/Inputs/RefMats/SkinSignaturesV1.0.tsv predictions/DCQ_PBMC1NormMix_SkinSignaturesV1.tsv
./WrapperDCQ.sh /u/home/b/bnadel/Benchmarking/Inputs/Mixes/PBMC2NormMix.tsv /u/home/b/bnadel/Benchmarking/Inputs/RefMats/10XImmune.tsv predictions/DCQ_PBMC2NormMix_10XImmune.tsv
./WrapperDCQ.sh /u/home/b/bnadel/Benchmarking/Inputs/Mixes/PBMC2NormMix.tsv /u/home/b/bnadel/Benchmarking/Inputs/RefMats/BlueCodeV1.0.tsv predictions/DCQ_PBMC2NormMix_BlueCodeV1.tsv
./WrapperDCQ.sh /u/home/b/bnadel/Benchmarking/Inputs/Mixes/PBMC2NormMix.tsv /u/home/b/bnadel/Benchmarking/Inputs/RefMats/BluePrint-Blood.tsv predictions/DCQ_PBMC2NormMix_BluePrint-Blood.tsv
./WrapperDCQ.sh /u/home/b/bnadel/Benchmarking/Inputs/Mixes/PBMC2NormMix.tsv /u/home/b/bnadel/Benchmarking/Inputs/RefMats/EPIC-BCIC.tsv predictions/DCQ_PBMC2NormMix_EPIC-BCIC.tsv
./WrapperDCQ.sh /u/home/b/bnadel/Benchmarking/Inputs/Mixes/PBMC2NormMix.tsv /u/home/b/bnadel/Benchmarking/Inputs/RefMats/EPIC-TIC.tsv predictions/DCQ_PBMC2NormMix_EPIC-TIC.tsv
./WrapperDCQ.sh /u/home/b/bnadel/Benchmarking/Inputs/Mixes/PBMC2NormMix.tsv /u/home/b/bnadel/Benchmarking/Inputs/RefMats/HPCA-Blood.tsv predictions/DCQ_PBMC2NormMix_HPCA-Blood.tsv
./WrapperDCQ.sh /u/home/b/bnadel/Benchmarking/Inputs/Mixes/PBMC2NormMix.tsv /u/home/b/bnadel/Benchmarking/Inputs/RefMats/HPCA-Stromal.tsv predictions/DCQ_PBMC2NormMix_HPCA-Stromal.tsv
./WrapperDCQ.sh /u/home/b/bnadel/Benchmarking/Inputs/Mixes/PBMC2NormMix.tsv /u/home/b/bnadel/Benchmarking/Inputs/RefMats/ImmunoStates-Blood.tsv predictions/DCQ_PBMC2NormMix_ImmunoStates-Blood.tsv
./WrapperDCQ.sh /u/home/b/bnadel/Benchmarking/Inputs/Mixes/PBMC2NormMix.tsv /u/home/b/bnadel/Benchmarking/Inputs/RefMats/ImmunoStates-Full.tsv predictions/DCQ_PBMC2NormMix_ImmunoStates-Full.tsv
./WrapperDCQ.sh /u/home/b/bnadel/Benchmarking/Inputs/Mixes/PBMC2NormMix.tsv /u/home/b/bnadel/Benchmarking/Inputs/RefMats/ImmunoStates-Stromal.tsv predictions/DCQ_PBMC2NormMix_ImmunoStates-Stromal.tsv
./WrapperDCQ.sh /u/home/b/bnadel/Benchmarking/Inputs/Mixes/PBMC2NormMix.tsv /u/home/b/bnadel/Benchmarking/Inputs/RefMats/LM22-Blood.tsv predictions/DCQ_PBMC2NormMix_LM22-Blood.tsv
./WrapperDCQ.sh /u/home/b/bnadel/Benchmarking/Inputs/Mixes/PBMC2NormMix.tsv /u/home/b/bnadel/Benchmarking/Inputs/RefMats/LM22-Full.tsv predictions/DCQ_PBMC2NormMix_LM22-Full.tsv
./WrapperDCQ.sh /u/home/b/bnadel/Benchmarking/Inputs/Mixes/PBMC2NormMix.tsv /u/home/b/bnadel/Benchmarking/Inputs/RefMats/LM22-Stromal.tsv predictions/DCQ_PBMC2NormMix_LM22-Stromal.tsv
./WrapperDCQ.sh /u/home/b/bnadel/Benchmarking/Inputs/Mixes/PBMC2NormMix.tsv /u/home/b/bnadel/Benchmarking/Inputs/RefMats/SkinSignaturesV1.0.tsv predictions/DCQ_PBMC2NormMix_SkinSignaturesV1.tsv
./WrapperDCQ.sh /u/home/b/bnadel/Benchmarking/Inputs/Mixes/StromalNormMix.tsv /u/home/b/bnadel/Benchmarking/Inputs/RefMats/10XImmune.tsv predictions/DCQ_StromalNormMix_10XImmune.tsv
./WrapperDCQ.sh /u/home/b/bnadel/Benchmarking/Inputs/Mixes/StromalNormMix.tsv /u/home/b/bnadel/Benchmarking/Inputs/RefMats/BlueCodeV1.0.tsv predictions/DCQ_StromalNormMix_BlueCodeV1.tsv
./WrapperDCQ.sh /u/home/b/bnadel/Benchmarking/Inputs/Mixes/StromalNormMix.tsv /u/home/b/bnadel/Benchmarking/Inputs/RefMats/BluePrint-Blood.tsv predictions/DCQ_StromalNormMix_BluePrint-Blood.tsv
./WrapperDCQ.sh /u/home/b/bnadel/Benchmarking/Inputs/Mixes/StromalNormMix.tsv /u/home/b/bnadel/Benchmarking/Inputs/RefMats/EPIC-BCIC.tsv predictions/DCQ_StromalNormMix_EPIC-BCIC.tsv
./WrapperDCQ.sh /u/home/b/bnadel/Benchmarking/Inputs/Mixes/StromalNormMix.tsv /u/home/b/bnadel/Benchmarking/Inputs/RefMats/EPIC-TIC.tsv predictions/DCQ_StromalNormMix_EPIC-TIC.tsv
./WrapperDCQ.sh /u/home/b/bnadel/Benchmarking/Inputs/Mixes/StromalNormMix.tsv /u/home/b/bnadel/Benchmarking/Inputs/RefMats/HPCA-Blood.tsv predictions/DCQ_StromalNormMix_HPCA-Blood.tsv
./WrapperDCQ.sh /u/home/b/bnadel/Benchmarking/Inputs/Mixes/StromalNormMix.tsv /u/home/b/bnadel/Benchmarking/Inputs/RefMats/HPCA-Stromal.tsv predictions/DCQ_StromalNormMix_HPCA-Stromal.tsv
./WrapperDCQ.sh /u/home/b/bnadel/Benchmarking/Inputs/Mixes/StromalNormMix.tsv /u/home/b/bnadel/Benchmarking/Inputs/RefMats/ImmunoStates-Blood.tsv predictions/DCQ_StromalNormMix_ImmunoStates-Blood.tsv
./WrapperDCQ.sh /u/home/b/bnadel/Benchmarking/Inputs/Mixes/StromalNormMix.tsv /u/home/b/bnadel/Benchmarking/Inputs/RefMats/ImmunoStates-Full.tsv predictions/DCQ_StromalNormMix_ImmunoStates-Full.tsv
./WrapperDCQ.sh /u/home/b/bnadel/Benchmarking/Inputs/Mixes/StromalNormMix.tsv /u/home/b/bnadel/Benchmarking/Inputs/RefMats/ImmunoStates-Stromal.tsv predictions/DCQ_StromalNormMix_ImmunoStates-Stromal.tsv
./WrapperDCQ.sh /u/home/b/bnadel/Benchmarking/Inputs/Mixes/StromalNormMix.tsv /u/home/b/bnadel/Benchmarking/Inputs/RefMats/LM22-Blood.tsv predictions/DCQ_StromalNormMix_LM22-Blood.tsv
./WrapperDCQ.sh /u/home/b/bnadel/Benchmarking/Inputs/Mixes/StromalNormMix.tsv /u/home/b/bnadel/Benchmarking/Inputs/RefMats/LM22-Full.tsv predictions/DCQ_StromalNormMix_LM22-Full.tsv
./WrapperDCQ.sh /u/home/b/bnadel/Benchmarking/Inputs/Mixes/StromalNormMix.tsv /u/home/b/bnadel/Benchmarking/Inputs/RefMats/LM22-Stromal.tsv predictions/DCQ_StromalNormMix_LM22-Stromal.tsv
./WrapperDCQ.sh /u/home/b/bnadel/Benchmarking/Inputs/Mixes/StromalNormMix.tsv /u/home/b/bnadel/Benchmarking/Inputs/RefMats/SkinSignaturesV1.0.tsv predictions/DCQ_StromalNormMix_SkinSignaturesV1.tsv
